/*
 * generated by Xtext
 */
package formulario;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FormularioStandaloneSetup extends FormularioStandaloneSetupGenerated{

	public static void doSetup() {
		new FormularioStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

