/**
 * generated by Xtext
 */
package formulario.serializer;

import formulario.serializer.AbstractFormularioSemanticSequencer;

@SuppressWarnings("all")
public class FormularioSemanticSequencer extends AbstractFormularioSemanticSequencer {
}
