/**
 * generated by Xtext
 */
package formulario.generator;

import Formularios_DASOFT.Accion;
import Formularios_DASOFT.AccionSeleccion;
import Formularios_DASOFT.AccionValor;
import Formularios_DASOFT.Asercion;
import Formularios_DASOFT.AsercionHabilitado;
import Formularios_DASOFT.AsercionInvisible;
import Formularios_DASOFT.AsercionSeleccion;
import Formularios_DASOFT.AsercionValor;
import Formularios_DASOFT.Formulario;
import Formularios_DASOFT.Input;
import Formularios_DASOFT.InputBoton;
import Formularios_DASOFT.InputCheck;
import Formularios_DASOFT.InputCombo;
import Formularios_DASOFT.InputRadio;
import Formularios_DASOFT.InputTexto;
import Formularios_DASOFT.Layout;
import Formularios_DASOFT.PruebaInterfaz;
import Formularios_DASOFT.Reaccion;
import Formularios_DASOFT.ReaccionHabilitado;
import Formularios_DASOFT.ReaccionVisible;
import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FormularioGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Formulario> _filter = Iterables.<Formulario>filter(_iterable, Formulario.class);
    for (final Formulario form : _filter) {
      {
        CharSequence _generarFormulario = this.generarFormulario(form);
        fsa.generateFile("forms/Formulario.java", _generarFormulario);
        PruebaInterfaz _pruebas = form.getPruebas();
        CharSequence _generarTest = this.generarTest(_pruebas);
        fsa.generateFile("../tests/forms/FormularioTest.java", _generarTest);
      }
    }
  }
  
  public CharSequence generarFormulario(final Formulario form) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package forms;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.swt.SWT;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.events.SelectionEvent;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.events.SelectionListener;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.layout.GridData;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.layout.GridLayout;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Button;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Combo;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Display;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Composite;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Label;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Shell;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Text;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class Formulario {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Display display = new Display();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Shell   shell   = new Formulario().showForm(display);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("while (!shell.isDisposed()) ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (!display.readAndDispatch())");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("display.sleep();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("display.dispose();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Shell showForm(Display display) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Shell shell = new Shell(display);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("shell.setText  (\"");
    String _name = form.getName();
    _builder.append(_name, "\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("shell.setLayout(new GridLayout(");
    Layout _layout = form.getLayout();
    int _columnas = _layout.getColumnas();
    _builder.append(_columnas, "\t\t");
    _builder.append(", false));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Añadimos los elementos de la interfaz");
    _builder.newLine();
    {
      Layout _layout_1 = form.getLayout();
      EList<Input> _entradas = _layout_1.getEntradas();
      for(final Input input : _entradas) {
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        {
          if ((input instanceof InputBoton)) {
            _builder.append("// CASO BOTONES");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("Button boton");
            String _name_1 = ((InputBoton)input).getName();
            _builder.append(_name_1, "\t\t");
            _builder.append(" = new Button(shell, SWT.CHECK);");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("boton");
            String _name_2 = ((InputBoton)input).getName();
            _builder.append(_name_2, "\t\t");
            _builder.append(".setText(\"");
            String _name_3 = ((InputBoton)input).getName();
            _builder.append(_name_3, "\t\t");
            _builder.append("\");");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
          } else {
            if ((input instanceof InputTexto)) {
              _builder.append("// CASO TEXTO");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              _builder.append("Composite contentText");
              String _name_4 = input.getName();
              _builder.append(_name_4, "\t\t");
              _builder.append(" = new Composite(shell, SWT.BORDER);");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              _builder.append("contentText");
              String _name_5 = input.getName();
              _builder.append(_name_5, "\t\t");
              _builder.append(".setLayout(new GridLayout(2, true));");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              _builder.append("Label label");
              String _name_6 = input.getName();
              _builder.append(_name_6, "\t\t");
              _builder.append(" = new Label(contentText");
              String _name_7 = input.getName();
              _builder.append(_name_7, "\t\t");
              _builder.append(", SWT.NONE);");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              _builder.append("Text  texto");
              String _name_8 = input.getName();
              _builder.append(_name_8, "\t\t");
              _builder.append("  = new Text(contentText");
              String _name_9 = input.getName();
              _builder.append(_name_9, "\t\t");
              _builder.append(", SWT.BORDER);");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              _builder.append("label");
              String _name_10 = input.getName();
              _builder.append(_name_10, "\t\t");
              _builder.append(".setText(\"");
              String _name_11 = input.getName();
              _builder.append(_name_11, "\t\t");
              _builder.append("\");");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
            } else {
              if ((input instanceof InputCheck)) {
                _builder.append("// CASO CHECKBOX");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.append("Composite contentCheck");
                String _name_12 = input.getName();
                _builder.append(_name_12, "\t\t");
                _builder.append(" = new Composite(shell, SWT.BORDER);");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.append("contentCheck");
                String _name_13 = input.getName();
                _builder.append(_name_13, "\t\t");
                _builder.append(".setLayout(new GridLayout(1, true));");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.append("Button[] check");
                String _name_14 = input.getName();
                _builder.append(_name_14, "\t\t");
                _builder.append(" = new Button[");
                EList<String> _valores = ((InputCheck) input).getValores();
                int _size = _valores.size();
                _builder.append(_size, "\t\t");
                _builder.append("];");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.newLine();
                {
                  EList<String> _valores_1 = ((InputCheck) input).getValores();
                  for(final String valor : _valores_1) {
                    _builder.append("\t\t");
                    _builder.append("check");
                    String _name_15 = input.getName();
                    _builder.append(_name_15, "\t\t");
                    _builder.append("[");
                    EList<String> _valores_2 = ((InputCheck) input).getValores();
                    int _indexOf = _valores_2.indexOf(valor);
                    _builder.append(_indexOf, "\t\t");
                    _builder.append("] = new Button(contentCheck");
                    String _name_16 = input.getName();
                    _builder.append(_name_16, "\t\t");
                    _builder.append(", SWT.CHECK);");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t");
                    _builder.append("check");
                    String _name_17 = input.getName();
                    _builder.append(_name_17, "\t\t");
                    _builder.append("[");
                    EList<String> _valores_3 = ((InputCheck) input).getValores();
                    int _indexOf_1 = _valores_3.indexOf(valor);
                    _builder.append(_indexOf_1, "\t\t");
                    _builder.append("].setText(\"");
                    _builder.append(valor, "\t\t");
                    _builder.append("\");");
                    _builder.newLineIfNotEmpty();
                  }
                }
                _builder.append("\t\t");
              } else {
                if ((input instanceof InputRadio)) {
                  _builder.append("// CASO RADIO");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                  _builder.append("Composite contentRadio");
                  String _name_18 = input.getName();
                  _builder.append(_name_18, "\t\t");
                  _builder.append(" = new Composite(shell, SWT.BORDER);");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                  _builder.append("contentRadio");
                  String _name_19 = input.getName();
                  _builder.append(_name_19, "\t\t");
                  _builder.append(".setLayout(new GridLayout(1, true));");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                  _builder.append("Button[] radio");
                  String _name_20 = input.getName();
                  _builder.append(_name_20, "\t\t");
                  _builder.append(" = new Button[");
                  EList<String> _valores_4 = ((InputRadio) input).getValores();
                  int _size_1 = _valores_4.size();
                  _builder.append(_size_1, "\t\t");
                  _builder.append("];");
                  _builder.newLineIfNotEmpty();
                  _builder.newLine();
                  {
                    EList<String> _valores_5 = ((InputRadio) input).getValores();
                    for(final String valor_1 : _valores_5) {
                      _builder.append("\t\t");
                      _builder.append("radio");
                      String _name_21 = input.getName();
                      _builder.append(_name_21, "\t\t");
                      _builder.append("[");
                      EList<String> _valores_6 = ((InputRadio) input).getValores();
                      int _indexOf_2 = _valores_6.indexOf(valor_1);
                      _builder.append(_indexOf_2, "\t\t");
                      _builder.append("] = new Button(contentRadio");
                      String _name_22 = input.getName();
                      _builder.append(_name_22, "\t\t");
                      _builder.append(", SWT.RADIO);");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("radio");
                      String _name_23 = input.getName();
                      _builder.append(_name_23, "\t\t");
                      _builder.append("[");
                      EList<String> _valores_7 = ((InputRadio) input).getValores();
                      int _indexOf_3 = _valores_7.indexOf(valor_1);
                      _builder.append(_indexOf_3, "\t\t");
                      _builder.append("].setSelection(false);");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("radio");
                      String _name_24 = input.getName();
                      _builder.append(_name_24, "\t\t");
                      _builder.append("[");
                      EList<String> _valores_8 = ((InputRadio) input).getValores();
                      int _indexOf_4 = _valores_8.indexOf(valor_1);
                      _builder.append(_indexOf_4, "\t\t");
                      _builder.append("].setText(\"");
                      _builder.append(valor_1, "\t\t");
                      _builder.append("\");");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("radio");
                      String _name_25 = input.getName();
                      _builder.append(_name_25, "\t\t");
                      _builder.append("[");
                      EList<String> _valores_9 = ((InputRadio) input).getValores();
                      int _indexOf_5 = _valores_9.indexOf(valor_1);
                      _builder.append(_indexOf_5, "\t\t");
                      _builder.append("].setBounds(10, 5, 75, 30);");
                      _builder.newLineIfNotEmpty();
                    }
                  }
                  _builder.append("\t\t");
                } else {
                  if ((input instanceof InputCombo)) {
                    _builder.append(" // CASO COMBO");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t");
                    _builder.append("Combo combo");
                    String _name_26 = input.getName();
                    _builder.append(_name_26, "\t\t");
                    _builder.append(" = new Combo(shell, SWT.SIMPLE);");
                    _builder.newLineIfNotEmpty();
                    {
                      EList<String> _valores_10 = ((InputCombo) input).getValores();
                      for(final String valor_2 : _valores_10) {
                        _builder.append("\t\t");
                        _builder.append("combo");
                        String _name_27 = input.getName();
                        _builder.append(_name_27, "\t\t");
                        _builder.append(".add(\"");
                        _builder.append(valor_2, "\t\t");
                        _builder.append("\");");
                        _builder.newLineIfNotEmpty();
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// layout");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("GridData data = new GridData(SWT.FILL, SWT.FILL, true, false);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("data.horizontalSpan = 2;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("//checkCash.setLayoutData(data);\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// checkbutton");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Button checkCash = new Button(shell, SWT.CHECK);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.setText(\"Pay with cash?\");\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// text field");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Label labelCCNumber = new Label(shell, SWT.NONE);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Text  textCCNumber  = new Text(shell, SWT.BORDER);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("labelCCNumber.setText(\"Credit card number\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// layout");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("GridData data = new GridData(SWT.FILL, SWT.FILL, true, false);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("shell.setLayout(new GridLayout(2, true));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("data.horizontalSpan = 2;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.setLayoutData(data);\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("**/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Funciones Reaccion");
    _builder.newLine();
    {
      Layout _layout_2 = form.getLayout();
      EList<Input> _entradas_1 = _layout_2.getEntradas();
      for(final Input input_1 : _entradas_1) {
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("//");
        Class<? extends Input> _class = input_1.getClass();
        String _name_28 = _class.getName();
        _builder.append(_name_28, "\t\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        {
          if ((input_1 instanceof InputCheck)) {
            _builder.append("// CASO CHECKBOX");
            _builder.newLineIfNotEmpty();
            {
              Reaccion _reaccion = ((InputCheck) input_1).getReaccion();
              boolean _notEquals = (!Objects.equal(_reaccion, null));
              if (_notEquals) {
                {
                  Reaccion _reaccion_1 = ((InputCheck) input_1).getReaccion();
                  if ((_reaccion_1 instanceof ReaccionVisible)) {
                    _builder.append("\t\t");
                    _builder.append("check");
                    String _name_29 = ((InputCheck)input_1).getName();
                    _builder.append(_name_29, "\t\t");
                    _builder.append("[");
                    Reaccion _reaccion_2 = ((InputCheck) input_1).getReaccion();
                    int _activacion = _reaccion_2.getActivacion();
                    _builder.append(_activacion, "\t\t");
                    _builder.append("].addSelectionListener(new SelectionListener() {");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.append("@Override");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.append("public void widgetSelected(SelectionEvent arg0) {");
                    _builder.newLine();
                    {
                      Reaccion _reaccion_3 = ((InputCheck) input_1).getReaccion();
                      Input _objetivo = _reaccion_3.getObjetivo();
                      if ((_objetivo instanceof InputBoton)) {
                        _builder.append("\t\t");
                        _builder.append("\t\t");
                        _builder.append("boton");
                        Reaccion _reaccion_4 = ((InputCheck) input_1).getReaccion();
                        Input _objetivo_1 = _reaccion_4.getObjetivo();
                        String _name_30 = _objetivo_1.getName();
                        _builder.append(_name_30, "\t\t\t\t");
                        _builder.append(".setVisible( !check");
                        String _name_31 = ((InputCheck)input_1).getName();
                        _builder.append(_name_31, "\t\t\t\t");
                        _builder.append("[");
                        Reaccion _reaccion_5 = ((InputCheck) input_1).getReaccion();
                        int _activacion_1 = _reaccion_5.getActivacion();
                        _builder.append(_activacion_1, "\t\t\t\t");
                        _builder.append("].getSelection() );");
                        _builder.newLineIfNotEmpty();
                      } else {
                        Reaccion _reaccion_6 = ((InputCheck) input_1).getReaccion();
                        Input _objetivo_2 = _reaccion_6.getObjetivo();
                        if ((_objetivo_2 instanceof InputTexto)) {
                          _builder.append("\t\t");
                          _builder.append("\t\t");
                          _builder.append("texto");
                          Reaccion _reaccion_7 = ((InputCheck) input_1).getReaccion();
                          Input _objetivo_3 = _reaccion_7.getObjetivo();
                          String _name_32 = _objetivo_3.getName();
                          _builder.append(_name_32, "\t\t\t\t");
                          _builder.append(".setVisible( !check");
                          String _name_33 = ((InputCheck)input_1).getName();
                          _builder.append(_name_33, "\t\t\t\t");
                          _builder.append("[");
                          Reaccion _reaccion_8 = ((InputCheck) input_1).getReaccion();
                          int _activacion_2 = _reaccion_8.getActivacion();
                          _builder.append(_activacion_2, "\t\t\t\t");
                          _builder.append("].getSelection() );");
                          _builder.newLineIfNotEmpty();
                        } else {
                          Reaccion _reaccion_9 = ((InputCheck) input_1).getReaccion();
                          Input _objetivo_4 = _reaccion_9.getObjetivo();
                          if ((_objetivo_4 instanceof InputCheck)) {
                            _builder.append("\t\t");
                            _builder.append("\t\t");
                            _builder.append("check");
                            Reaccion _reaccion_10 = ((InputCheck) input_1).getReaccion();
                            Input _objetivo_5 = _reaccion_10.getObjetivo();
                            String _name_34 = _objetivo_5.getName();
                            _builder.append(_name_34, "\t\t\t\t");
                            _builder.append(".setVisible( !check");
                            String _name_35 = ((InputCheck)input_1).getName();
                            _builder.append(_name_35, "\t\t\t\t");
                            _builder.append("[");
                            Reaccion _reaccion_11 = ((InputCheck) input_1).getReaccion();
                            int _activacion_3 = _reaccion_11.getActivacion();
                            _builder.append(_activacion_3, "\t\t\t\t");
                            _builder.append("].getSelection() );");
                            _builder.newLineIfNotEmpty();
                          } else {
                            Reaccion _reaccion_12 = ((InputCheck) input_1).getReaccion();
                            Input _objetivo_6 = _reaccion_12.getObjetivo();
                            if ((_objetivo_6 instanceof InputCombo)) {
                              _builder.append("\t\t");
                              _builder.append("\t\t");
                              _builder.append("combo");
                              Reaccion _reaccion_13 = ((InputCheck) input_1).getReaccion();
                              Input _objetivo_7 = _reaccion_13.getObjetivo();
                              String _name_36 = _objetivo_7.getName();
                              _builder.append(_name_36, "\t\t\t\t");
                              _builder.append(".setVisible( !check");
                              String _name_37 = ((InputCheck)input_1).getName();
                              _builder.append(_name_37, "\t\t\t\t");
                              _builder.append("[");
                              Reaccion _reaccion_14 = ((InputCheck) input_1).getReaccion();
                              int _activacion_4 = _reaccion_14.getActivacion();
                              _builder.append(_activacion_4, "\t\t\t\t");
                              _builder.append("].getSelection() );");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Reaccion _reaccion_15 = ((InputCheck) input_1).getReaccion();
                              Input _objetivo_8 = _reaccion_15.getObjetivo();
                              if ((_objetivo_8 instanceof InputRadio)) {
                                _builder.append("\t\t");
                                _builder.append("\t\t");
                                _builder.append("radio");
                                Reaccion _reaccion_16 = ((InputCheck) input_1).getReaccion();
                                Input _objetivo_9 = _reaccion_16.getObjetivo();
                                String _name_38 = _objetivo_9.getName();
                                _builder.append(_name_38, "\t\t\t\t");
                                _builder.append(".setVisible( !check");
                                String _name_39 = ((InputCheck)input_1).getName();
                                _builder.append(_name_39, "\t\t\t\t");
                                _builder.append("[");
                                Reaccion _reaccion_17 = ((InputCheck) input_1).getReaccion();
                                int _activacion_5 = _reaccion_17.getActivacion();
                                _builder.append(_activacion_5, "\t\t\t\t");
                                _builder.append("].getSelection() );");
                                _builder.newLineIfNotEmpty();
                              }
                            }
                          }
                        }
                      }
                    }
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.append("}");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.append("@Override");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("\t");
                    _builder.append("public void widgetDefaultSelected(SelectionEvent arg0) {}");
                    _builder.newLine();
                    _builder.append("\t\t");
                    _builder.append("});");
                    _builder.newLine();
                  } else {
                    Reaccion _reaccion_18 = ((InputCheck) input_1).getReaccion();
                    if ((_reaccion_18 instanceof ReaccionHabilitado)) {
                      _builder.append("\t\t");
                      _builder.append("check");
                      String _name_40 = ((InputCheck)input_1).getName();
                      _builder.append(_name_40, "\t\t");
                      _builder.append("[");
                      Reaccion _reaccion_19 = ((InputCheck) input_1).getReaccion();
                      int _activacion_6 = _reaccion_19.getActivacion();
                      _builder.append(_activacion_6, "\t\t");
                      _builder.append("].addSelectionListener(new SelectionListener() {");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("@Override");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("public void widgetSelected(SelectionEvent arg0) {");
                      _builder.newLine();
                      {
                        Reaccion _reaccion_20 = ((InputCheck) input_1).getReaccion();
                        Input _objetivo_10 = _reaccion_20.getObjetivo();
                        if ((_objetivo_10 instanceof InputBoton)) {
                          _builder.append("\t\t");
                          _builder.append("\t\t");
                          _builder.append("boton");
                          Reaccion _reaccion_21 = ((InputCheck) input_1).getReaccion();
                          Input _objetivo_11 = _reaccion_21.getObjetivo();
                          String _name_41 = _objetivo_11.getName();
                          _builder.append(_name_41, "\t\t\t\t");
                          _builder.append(".setEnabled( !check");
                          String _name_42 = ((InputCheck)input_1).getName();
                          _builder.append(_name_42, "\t\t\t\t");
                          _builder.append("[");
                          Reaccion _reaccion_22 = ((InputCheck) input_1).getReaccion();
                          int _activacion_7 = _reaccion_22.getActivacion();
                          _builder.append(_activacion_7, "\t\t\t\t");
                          _builder.append("].getSelection() );");
                          _builder.newLineIfNotEmpty();
                        } else {
                          Reaccion _reaccion_23 = ((InputCheck) input_1).getReaccion();
                          Input _objetivo_12 = _reaccion_23.getObjetivo();
                          if ((_objetivo_12 instanceof InputTexto)) {
                            _builder.append("\t\t");
                            _builder.append("\t\t");
                            _builder.append("texto");
                            Reaccion _reaccion_24 = ((InputCheck) input_1).getReaccion();
                            Input _objetivo_13 = _reaccion_24.getObjetivo();
                            String _name_43 = _objetivo_13.getName();
                            _builder.append(_name_43, "\t\t\t\t");
                            _builder.append(".setEnabled( !check");
                            String _name_44 = ((InputCheck)input_1).getName();
                            _builder.append(_name_44, "\t\t\t\t");
                            _builder.append("[");
                            Reaccion _reaccion_25 = ((InputCheck) input_1).getReaccion();
                            int _activacion_8 = _reaccion_25.getActivacion();
                            _builder.append(_activacion_8, "\t\t\t\t");
                            _builder.append("].getSelection() );");
                            _builder.newLineIfNotEmpty();
                          } else {
                            Reaccion _reaccion_26 = ((InputCheck) input_1).getReaccion();
                            Input _objetivo_14 = _reaccion_26.getObjetivo();
                            if ((_objetivo_14 instanceof InputCheck)) {
                              _builder.append("\t\t");
                              _builder.append("\t\t");
                              _builder.append("check");
                              Reaccion _reaccion_27 = ((InputCheck) input_1).getReaccion();
                              Input _objetivo_15 = _reaccion_27.getObjetivo();
                              String _name_45 = _objetivo_15.getName();
                              _builder.append(_name_45, "\t\t\t\t");
                              _builder.append(".setEnabled( !check");
                              String _name_46 = ((InputCheck)input_1).getName();
                              _builder.append(_name_46, "\t\t\t\t");
                              _builder.append("[");
                              Reaccion _reaccion_28 = ((InputCheck) input_1).getReaccion();
                              int _activacion_9 = _reaccion_28.getActivacion();
                              _builder.append(_activacion_9, "\t\t\t\t");
                              _builder.append("].getSelection() );");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Reaccion _reaccion_29 = ((InputCheck) input_1).getReaccion();
                              Input _objetivo_16 = _reaccion_29.getObjetivo();
                              if ((_objetivo_16 instanceof InputCombo)) {
                                _builder.append("\t\t");
                                _builder.append("\t\t");
                                _builder.append("combo");
                                Reaccion _reaccion_30 = ((InputCheck) input_1).getReaccion();
                                Input _objetivo_17 = _reaccion_30.getObjetivo();
                                String _name_47 = _objetivo_17.getName();
                                _builder.append(_name_47, "\t\t\t\t");
                                _builder.append(".setEnabled( !check");
                                String _name_48 = ((InputCheck)input_1).getName();
                                _builder.append(_name_48, "\t\t\t\t");
                                _builder.append("[");
                                Reaccion _reaccion_31 = ((InputCheck) input_1).getReaccion();
                                int _activacion_10 = _reaccion_31.getActivacion();
                                _builder.append(_activacion_10, "\t\t\t\t");
                                _builder.append("].getSelection() );");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Reaccion _reaccion_32 = ((InputCheck) input_1).getReaccion();
                                Input _objetivo_18 = _reaccion_32.getObjetivo();
                                if ((_objetivo_18 instanceof InputRadio)) {
                                  _builder.append("\t\t");
                                  _builder.append("\t\t");
                                  _builder.append("radio");
                                  Reaccion _reaccion_33 = ((InputCheck) input_1).getReaccion();
                                  Input _objetivo_19 = _reaccion_33.getObjetivo();
                                  String _name_49 = _objetivo_19.getName();
                                  _builder.append(_name_49, "\t\t\t\t");
                                  _builder.append(".setEnabled( !check");
                                  String _name_50 = ((InputCheck)input_1).getName();
                                  _builder.append(_name_50, "\t\t\t\t");
                                  _builder.append("[");
                                  Reaccion _reaccion_34 = ((InputCheck) input_1).getReaccion();
                                  int _activacion_11 = _reaccion_34.getActivacion();
                                  _builder.append(_activacion_11, "\t\t\t\t");
                                  _builder.append("].getSelection() );");
                                  _builder.newLineIfNotEmpty();
                                }
                              }
                            }
                          }
                        }
                      }
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("}");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("@Override");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("public void widgetDefaultSelected(SelectionEvent arg0) {}");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("});");
                      _builder.newLine();
                    }
                  }
                }
              }
            }
            _builder.append("\t\t");
          } else {
            if ((input_1 instanceof InputRadio)) {
              _builder.append("// CASO RADIO");
              _builder.newLineIfNotEmpty();
              {
                Reaccion _reaccion_35 = ((InputRadio) input_1).getReaccion();
                boolean _notEquals_1 = (!Objects.equal(_reaccion_35, null));
                if (_notEquals_1) {
                  {
                    Reaccion _reaccion_36 = ((InputRadio) input_1).getReaccion();
                    if ((_reaccion_36 instanceof ReaccionVisible)) {
                      _builder.append("\t\t");
                      _builder.append("radio");
                      String _name_51 = input_1.getName();
                      _builder.append(_name_51, "\t\t");
                      _builder.append("[");
                      Reaccion _reaccion_37 = ((InputRadio) input_1).getReaccion();
                      int _activacion_12 = _reaccion_37.getActivacion();
                      _builder.append(_activacion_12, "\t\t");
                      _builder.append("].addSelectionListener(new SelectionListener() {");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("@Override");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("public void widgetSelected(SelectionEvent arg0) {");
                      _builder.newLine();
                      {
                        Reaccion _reaccion_38 = ((InputRadio) input_1).getReaccion();
                        Input _objetivo_20 = _reaccion_38.getObjetivo();
                        if ((_objetivo_20 instanceof InputBoton)) {
                          _builder.append("\t\t");
                          _builder.append("\t\t");
                          _builder.append("boton");
                          Reaccion _reaccion_39 = ((InputRadio) input_1).getReaccion();
                          Input _objetivo_21 = _reaccion_39.getObjetivo();
                          String _name_52 = _objetivo_21.getName();
                          _builder.append(_name_52, "\t\t\t\t");
                          _builder.append(".setVisible( !radio");
                          String _name_53 = input_1.getName();
                          _builder.append(_name_53, "\t\t\t\t");
                          _builder.append("[");
                          Reaccion _reaccion_40 = ((InputRadio) input_1).getReaccion();
                          int _activacion_13 = _reaccion_40.getActivacion();
                          _builder.append(_activacion_13, "\t\t\t\t");
                          _builder.append("].getSelection() );");
                          _builder.newLineIfNotEmpty();
                        } else {
                          Reaccion _reaccion_41 = ((InputRadio) input_1).getReaccion();
                          Input _objetivo_22 = _reaccion_41.getObjetivo();
                          if ((_objetivo_22 instanceof InputTexto)) {
                            _builder.append("\t\t");
                            _builder.append("\t\t");
                            _builder.append("texto");
                            Reaccion _reaccion_42 = ((InputRadio) input_1).getReaccion();
                            Input _objetivo_23 = _reaccion_42.getObjetivo();
                            String _name_54 = _objetivo_23.getName();
                            _builder.append(_name_54, "\t\t\t\t");
                            _builder.append(".setVisible( !radio");
                            String _name_55 = input_1.getName();
                            _builder.append(_name_55, "\t\t\t\t");
                            _builder.append("[");
                            Reaccion _reaccion_43 = ((InputRadio) input_1).getReaccion();
                            int _activacion_14 = _reaccion_43.getActivacion();
                            _builder.append(_activacion_14, "\t\t\t\t");
                            _builder.append("].getSelection() );");
                            _builder.newLineIfNotEmpty();
                          } else {
                            Reaccion _reaccion_44 = ((InputRadio) input_1).getReaccion();
                            Input _objetivo_24 = _reaccion_44.getObjetivo();
                            if ((_objetivo_24 instanceof InputCheck)) {
                              _builder.append("\t\t");
                              _builder.append("\t\t");
                              _builder.append("check");
                              Reaccion _reaccion_45 = ((InputRadio) input_1).getReaccion();
                              Input _objetivo_25 = _reaccion_45.getObjetivo();
                              String _name_56 = _objetivo_25.getName();
                              _builder.append(_name_56, "\t\t\t\t");
                              _builder.append(".setVisible( !radio");
                              String _name_57 = input_1.getName();
                              _builder.append(_name_57, "\t\t\t\t");
                              _builder.append("[");
                              Reaccion _reaccion_46 = ((InputRadio) input_1).getReaccion();
                              int _activacion_15 = _reaccion_46.getActivacion();
                              _builder.append(_activacion_15, "\t\t\t\t");
                              _builder.append("].getSelection() );");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Reaccion _reaccion_47 = ((InputRadio) input_1).getReaccion();
                              Input _objetivo_26 = _reaccion_47.getObjetivo();
                              if ((_objetivo_26 instanceof InputCombo)) {
                                _builder.append("\t\t");
                                _builder.append("\t\t");
                                _builder.append("combo");
                                Reaccion _reaccion_48 = ((InputRadio) input_1).getReaccion();
                                Input _objetivo_27 = _reaccion_48.getObjetivo();
                                String _name_58 = _objetivo_27.getName();
                                _builder.append(_name_58, "\t\t\t\t");
                                _builder.append(".setVisible( !radio");
                                String _name_59 = input_1.getName();
                                _builder.append(_name_59, "\t\t\t\t");
                                _builder.append("[");
                                Reaccion _reaccion_49 = ((InputRadio) input_1).getReaccion();
                                int _activacion_16 = _reaccion_49.getActivacion();
                                _builder.append(_activacion_16, "\t\t\t\t");
                                _builder.append("].getSelection() );");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Reaccion _reaccion_50 = ((InputRadio) input_1).getReaccion();
                                Input _objetivo_28 = _reaccion_50.getObjetivo();
                                if ((_objetivo_28 instanceof InputRadio)) {
                                  _builder.append("\t\t");
                                  _builder.append("\t\t");
                                  _builder.append("radio");
                                  Reaccion _reaccion_51 = ((InputRadio) input_1).getReaccion();
                                  Input _objetivo_29 = _reaccion_51.getObjetivo();
                                  String _name_60 = _objetivo_29.getName();
                                  _builder.append(_name_60, "\t\t\t\t");
                                  _builder.append(".setVisible( !radio");
                                  String _name_61 = input_1.getName();
                                  _builder.append(_name_61, "\t\t\t\t");
                                  _builder.append("[");
                                  Reaccion _reaccion_52 = ((InputRadio) input_1).getReaccion();
                                  int _activacion_17 = _reaccion_52.getActivacion();
                                  _builder.append(_activacion_17, "\t\t\t\t");
                                  _builder.append("].getSelection() );");
                                  _builder.newLineIfNotEmpty();
                                }
                              }
                            }
                          }
                        }
                      }
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("}");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("@Override");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("\t");
                      _builder.append("public void widgetDefaultSelected(SelectionEvent arg0) {}");
                      _builder.newLine();
                      _builder.append("\t\t");
                      _builder.append("});");
                      _builder.newLine();
                    } else {
                      Reaccion _reaccion_53 = ((InputRadio) input_1).getReaccion();
                      if ((_reaccion_53 instanceof ReaccionHabilitado)) {
                        _builder.append("\t\t");
                        _builder.append("radio");
                        String _name_62 = input_1.getName();
                        _builder.append(_name_62, "\t\t");
                        _builder.append("[");
                        Reaccion _reaccion_54 = ((InputRadio) input_1).getReaccion();
                        int _activacion_18 = _reaccion_54.getActivacion();
                        _builder.append(_activacion_18, "\t\t");
                        _builder.append("].addSelectionListener(new SelectionListener() {");
                        _builder.newLineIfNotEmpty();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.append("@Override");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.append("public void widgetSelected(SelectionEvent arg0) {");
                        _builder.newLine();
                        {
                          Reaccion _reaccion_55 = ((InputRadio) input_1).getReaccion();
                          Input _objetivo_30 = _reaccion_55.getObjetivo();
                          if ((_objetivo_30 instanceof InputBoton)) {
                            _builder.append("\t\t");
                            _builder.append("\t\t");
                            _builder.append("boton");
                            Reaccion _reaccion_56 = ((InputRadio) input_1).getReaccion();
                            Input _objetivo_31 = _reaccion_56.getObjetivo();
                            String _name_63 = _objetivo_31.getName();
                            _builder.append(_name_63, "\t\t\t\t");
                            _builder.append(".setEnabled( !radio");
                            String _name_64 = input_1.getName();
                            _builder.append(_name_64, "\t\t\t\t");
                            _builder.append("[");
                            Reaccion _reaccion_57 = ((InputRadio) input_1).getReaccion();
                            int _activacion_19 = _reaccion_57.getActivacion();
                            _builder.append(_activacion_19, "\t\t\t\t");
                            _builder.append("].getSelection() );");
                            _builder.newLineIfNotEmpty();
                          } else {
                            Reaccion _reaccion_58 = ((InputRadio) input_1).getReaccion();
                            Input _objetivo_32 = _reaccion_58.getObjetivo();
                            if ((_objetivo_32 instanceof InputTexto)) {
                              _builder.append("\t\t");
                              _builder.append("\t\t");
                              _builder.append("texto");
                              Reaccion _reaccion_59 = ((InputRadio) input_1).getReaccion();
                              Input _objetivo_33 = _reaccion_59.getObjetivo();
                              String _name_65 = _objetivo_33.getName();
                              _builder.append(_name_65, "\t\t\t\t");
                              _builder.append(".setEnabled( !radio");
                              String _name_66 = input_1.getName();
                              _builder.append(_name_66, "\t\t\t\t");
                              _builder.append("[");
                              Reaccion _reaccion_60 = ((InputRadio) input_1).getReaccion();
                              int _activacion_20 = _reaccion_60.getActivacion();
                              _builder.append(_activacion_20, "\t\t\t\t");
                              _builder.append("].getSelection() );");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Reaccion _reaccion_61 = ((InputRadio) input_1).getReaccion();
                              Input _objetivo_34 = _reaccion_61.getObjetivo();
                              if ((_objetivo_34 instanceof InputCheck)) {
                                _builder.append("\t\t");
                                _builder.append("\t\t");
                                _builder.append("check");
                                Reaccion _reaccion_62 = ((InputRadio) input_1).getReaccion();
                                Input _objetivo_35 = _reaccion_62.getObjetivo();
                                String _name_67 = _objetivo_35.getName();
                                _builder.append(_name_67, "\t\t\t\t");
                                _builder.append(".setEnabled( !radio");
                                String _name_68 = input_1.getName();
                                _builder.append(_name_68, "\t\t\t\t");
                                _builder.append("[");
                                Reaccion _reaccion_63 = ((InputRadio) input_1).getReaccion();
                                int _activacion_21 = _reaccion_63.getActivacion();
                                _builder.append(_activacion_21, "\t\t\t\t");
                                _builder.append("].getSelection() );");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Reaccion _reaccion_64 = ((InputRadio) input_1).getReaccion();
                                Input _objetivo_36 = _reaccion_64.getObjetivo();
                                if ((_objetivo_36 instanceof InputCombo)) {
                                  _builder.append("\t\t");
                                  _builder.append("\t\t");
                                  _builder.append("combo");
                                  Reaccion _reaccion_65 = ((InputRadio) input_1).getReaccion();
                                  Input _objetivo_37 = _reaccion_65.getObjetivo();
                                  String _name_69 = _objetivo_37.getName();
                                  _builder.append(_name_69, "\t\t\t\t");
                                  _builder.append(".setEnabled( !radio");
                                  String _name_70 = input_1.getName();
                                  _builder.append(_name_70, "\t\t\t\t");
                                  _builder.append("[");
                                  Reaccion _reaccion_66 = ((InputRadio) input_1).getReaccion();
                                  int _activacion_22 = _reaccion_66.getActivacion();
                                  _builder.append(_activacion_22, "\t\t\t\t");
                                  _builder.append("].getSelection() );");
                                  _builder.newLineIfNotEmpty();
                                } else {
                                  Reaccion _reaccion_67 = ((InputRadio) input_1).getReaccion();
                                  Input _objetivo_38 = _reaccion_67.getObjetivo();
                                  if ((_objetivo_38 instanceof InputRadio)) {
                                    _builder.append("\t\t");
                                    _builder.append("\t\t");
                                    _builder.append("radio");
                                    Reaccion _reaccion_68 = ((InputRadio) input_1).getReaccion();
                                    Input _objetivo_39 = _reaccion_68.getObjetivo();
                                    String _name_71 = _objetivo_39.getName();
                                    _builder.append(_name_71, "\t\t\t\t");
                                    _builder.append(".setEnabled( !radio");
                                    String _name_72 = input_1.getName();
                                    _builder.append(_name_72, "\t\t\t\t");
                                    _builder.append("[");
                                    Reaccion _reaccion_69 = ((InputRadio) input_1).getReaccion();
                                    int _activacion_23 = _reaccion_69.getActivacion();
                                    _builder.append(_activacion_23, "\t\t\t\t");
                                    _builder.append("].getSelection() );");
                                    _builder.newLineIfNotEmpty();
                                  }
                                }
                              }
                            }
                          }
                        }
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.append("}");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.append("@Override");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("\t");
                        _builder.append("public void widgetDefaultSelected(SelectionEvent arg0) {}");
                        _builder.newLine();
                        _builder.append("\t\t");
                        _builder.append("});");
                        _builder.newLine();
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// show or hide text field depending on checkbutton selection");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.addSelectionListener(new SelectionListener() {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public void widgetSelected(SelectionEvent arg0) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("labelCCNumber.setVisible( !checkCash.getSelection() );");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("textCCNumber.setVisible ( !checkCash.getSelection() );");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public void widgetDefaultSelected(SelectionEvent arg0) {}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("});");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("**/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// show form");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("shell.pack();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("shell.open();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return shell;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generarTest(final PruebaInterfaz pruebas) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package forms;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import static org.junit.Assert.assertFalse;");
    _builder.newLine();
    _builder.append("import static org.junit.Assert.assertTrue;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Display;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Shell;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.SWTBot;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.utils.SWTBotPreferences;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.widgets.SWTBotCheckBox;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.widgets.SWTBotLabel;");
    _builder.newLine();
    _builder.append("import org.eclipse.swtbot.swt.finder.widgets.SWTBotText;");
    _builder.newLine();
    _builder.append("import org.junit.Before;");
    _builder.newLine();
    _builder.append("import org.junit.Test;");
    _builder.newLine();
    _builder.append("import org.junit.runner.RunWith;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@RunWith(SWTBotJunit4ClassRunner.class)");
    _builder.newLine();
    _builder.append("public class FormularioTest {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Display display;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Shell shell;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private SWTBot bot;");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Before");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setup() {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("display = new Display();");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("shell   = new Formulario().showForm(display);");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("bot     = new SWTBot(shell);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Test");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void test1() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// slow down execution");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("SWTBotPreferences.PLAYBACK_DELAY = 100;");
    _builder.newLine();
    _builder.newLine();
    {
      EList<Accion> _acciones = pruebas.getAcciones();
      for(final Accion accion : _acciones) {
        _builder.append("\t\t");
        {
          if ((accion instanceof AccionValor)) {
            _builder.append("// CASO ACCION VALOR");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            {
              Input _elemento = ((AccionValor)accion).getElemento();
              if ((_elemento instanceof InputBoton)) {
                _builder.append("// CASO BOTONES");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
                _builder.append("SWTBotButton boton");
                Input _elemento_1 = ((AccionValor)accion).getElemento();
                String _name = _elemento_1.getName();
                _builder.append(_name, "\t\t");
                _builder.append(" = bot.button(\"");
                Input _elemento_2 = ((AccionValor)accion).getElemento();
                String _name_1 = _elemento_2.getName();
                _builder.append(_name_1, "\t\t");
                _builder.append("\");");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t");
              } else {
                Input _elemento_3 = ((AccionValor)accion).getElemento();
                if ((_elemento_3 instanceof InputTexto)) {
                  _builder.append("// CASO TEXTO");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                  _builder.append("SWTBotText texto");
                  Input _elemento_4 = ((AccionValor)accion).getElemento();
                  String _name_2 = _elemento_4.getName();
                  _builder.append(_name_2, "\t\t");
                  _builder.append(" = bot.textWithLabel(\"");
                  Input _elemento_5 = ((AccionValor)accion).getElemento();
                  String _name_3 = _elemento_5.getName();
                  _builder.append(_name_3, "\t\t");
                  _builder.append("\");");
                  _builder.newLineIfNotEmpty();
                }
              }
            }
            _builder.append("\t\t");
          } else {
            if ((accion instanceof AccionSeleccion)) {
              _builder.append(" // CASO ACCION SELECCION");
              _builder.newLineIfNotEmpty();
              _builder.append("\t\t");
              {
                Input _elemento_6 = accion.getElemento();
                if ((_elemento_6 instanceof InputCombo)) {
                  _builder.append("// CASO COMBO");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                  _builder.append("SWTBotButton boton");
                  Input _elemento_7 = accion.getElemento();
                  String _name_4 = _elemento_7.getName();
                  _builder.append(_name_4, "\t\t");
                  _builder.append(" = bot.comboWithLabel(\"");
                  Input _elemento_8 = accion.getElemento();
                  EList<String> _valores = ((InputCheck) _elemento_8).getValores();
                  int _valor = ((AccionSeleccion) accion).getValor();
                  String _get = _valores.get(_valor);
                  _builder.append(_get, "\t\t");
                  _builder.append("\");");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t");
                } else {
                  Input _elemento_9 = accion.getElemento();
                  if ((_elemento_9 instanceof InputRadio)) {
                    _builder.append("// CASO RADIO");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t");
                    _builder.append("SWTBotButton texto");
                    Input _elemento_10 = accion.getElemento();
                    String _name_5 = _elemento_10.getName();
                    _builder.append(_name_5, "\t\t");
                    _builder.append(" = bot.button(\"");
                    Input _elemento_11 = accion.getElemento();
                    String _name_6 = _elemento_11.getName();
                    _builder.append(_name_6, "\t\t");
                    _builder.append("\");");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t");
                  } else {
                    Input _elemento_12 = accion.getElemento();
                    if ((_elemento_12 instanceof InputCheck)) {
                      _builder.append("// CASO CHECK");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t");
                      _builder.append("SWTBotCheckBox check");
                      Input _elemento_13 = accion.getElemento();
                      String _name_7 = _elemento_13.getName();
                      _builder.append(_name_7, "\t\t");
                      _builder.append(" = bot.checkBox(\"");
                      Input _elemento_14 = accion.getElemento();
                      EList<String> _valores_1 = ((InputCheck) _elemento_14).getValores();
                      int _valor_1 = ((AccionSeleccion) accion).getValor();
                      String _get_1 = _valores_1.get(_valor_1);
                      _builder.append(_get_1, "\t\t");
                      _builder.append("\");");
                      _builder.newLineIfNotEmpty();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/*");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("SWTBotCheckBox checkCash  = bot.checkBox(\"Pay with cash?\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("SWTBotText  textCCNumber  = bot.textWithLabel(\"Credit card number\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("SWTBotLabel labelCCNumber = bot.label(\"Credit card number\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Ahora codificamos los ASSERTS");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    {
      EList<Accion> _acciones_1 = pruebas.getAcciones();
      for(final Accion accion_1 : _acciones_1) {
        {
          Asercion _asercion = accion_1.getAsercion();
          if ((_asercion instanceof AsercionHabilitado)) {
            {
              Asercion _asercion_1 = accion_1.getAsercion();
              Input _elemento_15 = _asercion_1.getElemento();
              if ((_elemento_15 instanceof InputBoton)) {
                _builder.append("\t\t");
                _builder.append("assertTrue(boton");
                Asercion _asercion_2 = accion_1.getAsercion();
                Input _elemento_16 = _asercion_2.getElemento();
                String _name_8 = _elemento_16.getName();
                _builder.append(_name_8, "\t\t");
                _builder.append(".isEnabled());");
                _builder.newLineIfNotEmpty();
              } else {
                Asercion _asercion_3 = accion_1.getAsercion();
                Input _elemento_17 = _asercion_3.getElemento();
                if ((_elemento_17 instanceof InputTexto)) {
                  _builder.append("\t\t");
                  _builder.append("assertTrue(texto");
                  Asercion _asercion_4 = accion_1.getAsercion();
                  Input _elemento_18 = _asercion_4.getElemento();
                  String _name_9 = _elemento_18.getName();
                  _builder.append(_name_9, "\t\t");
                  _builder.append(".isEnabled());");
                  _builder.newLineIfNotEmpty();
                } else {
                  Asercion _asercion_5 = accion_1.getAsercion();
                  Input _elemento_19 = _asercion_5.getElemento();
                  if ((_elemento_19 instanceof InputCombo)) {
                    _builder.append("\t\t");
                    _builder.append("assertTrue(combo");
                    Asercion _asercion_6 = accion_1.getAsercion();
                    Input _elemento_20 = _asercion_6.getElemento();
                    String _name_10 = _elemento_20.getName();
                    _builder.append(_name_10, "\t\t");
                    _builder.append(".isEnabled());");
                    _builder.newLineIfNotEmpty();
                  } else {
                    Asercion _asercion_7 = accion_1.getAsercion();
                    Input _elemento_21 = _asercion_7.getElemento();
                    if ((_elemento_21 instanceof InputRadio)) {
                      _builder.append("\t\t");
                      _builder.append("assertTrue(radio");
                      Asercion _asercion_8 = accion_1.getAsercion();
                      Input _elemento_22 = _asercion_8.getElemento();
                      String _name_11 = _elemento_22.getName();
                      _builder.append(_name_11, "\t\t");
                      _builder.append(".isEnabled()); /// ESTAAAAAA MAAAAAAAAAAAAAAL");
                      _builder.newLineIfNotEmpty();
                    } else {
                      Asercion _asercion_9 = accion_1.getAsercion();
                      Input _elemento_23 = _asercion_9.getElemento();
                      if ((_elemento_23 instanceof InputCheck)) {
                        _builder.append("\t\t");
                        _builder.append("assertTrue(check");
                        Asercion _asercion_10 = accion_1.getAsercion();
                        Input _elemento_24 = _asercion_10.getElemento();
                        String _name_12 = _elemento_24.getName();
                        _builder.append(_name_12, "\t\t");
                        _builder.append(".isEnabled());");
                        _builder.newLineIfNotEmpty();
                      }
                    }
                  }
                }
              }
            }
          } else {
            Asercion _asercion_11 = accion_1.getAsercion();
            if ((_asercion_11 instanceof AsercionInvisible)) {
              {
                Asercion _asercion_12 = accion_1.getAsercion();
                Input _elemento_25 = _asercion_12.getElemento();
                if ((_elemento_25 instanceof InputBoton)) {
                  _builder.append("\t\t");
                  _builder.append("assertTrue(boton");
                  Asercion _asercion_13 = accion_1.getAsercion();
                  Input _elemento_26 = _asercion_13.getElemento();
                  String _name_13 = _elemento_26.getName();
                  _builder.append(_name_13, "\t\t");
                  _builder.append(".isVisible());");
                  _builder.newLineIfNotEmpty();
                } else {
                  Asercion _asercion_14 = accion_1.getAsercion();
                  Input _elemento_27 = _asercion_14.getElemento();
                  if ((_elemento_27 instanceof InputTexto)) {
                    _builder.append("\t\t");
                    _builder.append("assertTrue(texto");
                    Asercion _asercion_15 = accion_1.getAsercion();
                    Input _elemento_28 = _asercion_15.getElemento();
                    String _name_14 = _elemento_28.getName();
                    _builder.append(_name_14, "\t\t");
                    _builder.append(".isVisible());");
                    _builder.newLineIfNotEmpty();
                  } else {
                    Asercion _asercion_16 = accion_1.getAsercion();
                    Input _elemento_29 = _asercion_16.getElemento();
                    if ((_elemento_29 instanceof InputCombo)) {
                      _builder.append("\t\t");
                      _builder.append("assertTrue(combo");
                      Asercion _asercion_17 = accion_1.getAsercion();
                      Input _elemento_30 = _asercion_17.getElemento();
                      String _name_15 = _elemento_30.getName();
                      _builder.append(_name_15, "\t\t");
                      _builder.append(".isVisible());");
                      _builder.newLineIfNotEmpty();
                    } else {
                      Asercion _asercion_18 = accion_1.getAsercion();
                      Input _elemento_31 = _asercion_18.getElemento();
                      if ((_elemento_31 instanceof InputRadio)) {
                        _builder.append("\t\t");
                        _builder.append("assertTrue(radio");
                        Asercion _asercion_19 = accion_1.getAsercion();
                        Input _elemento_32 = _asercion_19.getElemento();
                        String _name_16 = _elemento_32.getName();
                        _builder.append(_name_16, "\t\t");
                        _builder.append(".isVisible()); /// ESTAAAAAA MAAAAAAAAAAAAAAL");
                        _builder.newLineIfNotEmpty();
                      } else {
                        Asercion _asercion_20 = accion_1.getAsercion();
                        Input _elemento_33 = _asercion_20.getElemento();
                        if ((_elemento_33 instanceof InputCheck)) {
                          _builder.append("\t\t");
                          _builder.append("assertTrue(check");
                          Asercion _asercion_21 = accion_1.getAsercion();
                          Input _elemento_34 = _asercion_21.getElemento();
                          String _name_17 = _elemento_34.getName();
                          _builder.append(_name_17, "\t\t");
                          _builder.append(".isVisible());");
                          _builder.newLineIfNotEmpty();
                        } else {
                          Asercion _asercion_22 = accion_1.getAsercion();
                          if ((_asercion_22 instanceof AsercionValor)) {
                          } else {
                            Asercion _asercion_23 = accion_1.getAsercion();
                            if ((_asercion_23 instanceof AsercionSeleccion)) {
                              {
                                Asercion _asercion_24 = accion_1.getAsercion();
                                Input _elemento_35 = _asercion_24.getElemento();
                                if ((_elemento_35 instanceof InputCheck)) {
                                  _builder.append("\t\t");
                                  _builder.append("assertTrue(check");
                                  Asercion _asercion_25 = accion_1.getAsercion();
                                  Input _elemento_36 = _asercion_25.getElemento();
                                  String _name_18 = _elemento_36.getName();
                                  _builder.append(_name_18, "\t\t");
                                  _builder.append(".isSelected());");
                                  _builder.newLineIfNotEmpty();
                                } else {
                                  Asercion _asercion_26 = accion_1.getAsercion();
                                  Input _elemento_37 = _asercion_26.getElemento();
                                  if ((_elemento_37 instanceof InputCombo)) {
                                    _builder.append("\t\t");
                                    _builder.append("assertTrue(combo");
                                    Asercion _asercion_27 = accion_1.getAsercion();
                                    Input _elemento_38 = _asercion_27.getElemento();
                                    String _name_19 = _elemento_38.getName();
                                    _builder.append(_name_19, "\t\t");
                                    _builder.append(".isSelected());");
                                    _builder.newLineIfNotEmpty();
                                  } else {
                                    Asercion _asercion_28 = accion_1.getAsercion();
                                    Input _elemento_39 = _asercion_28.getElemento();
                                    if ((_elemento_39 instanceof InputRadio)) {
                                      _builder.append("\t\t");
                                      _builder.append("assertTrue(radio");
                                      Asercion _asercion_29 = accion_1.getAsercion();
                                      Input _elemento_40 = _asercion_29.getElemento();
                                      String _name_20 = _elemento_40.getName();
                                      _builder.append(_name_20, "\t\t");
                                      _builder.append(".isSelected());");
                                      _builder.newLineIfNotEmpty();
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// select check");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.setFocus();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.select();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("display.update();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// checkbutton should be checked, text field should be hidden");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertTrue(checkCash.isChecked());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertFalse(textCCNumber.isVisible());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertFalse(labelCCNumber.isVisible());");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// deselect check");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.setFocus();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("checkCash.deselect();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("display.update();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// checkbutton should be unchecked, text field should be visible");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertFalse(checkCash.isChecked());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertTrue(textCCNumber.isVisible());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("assertTrue(labelCCNumber.isVisible());");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("display.dispose();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("shell.dispose();\t\t ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
