/*
 * generated by Xtext
 */
package formulario.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class FormularioGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FormularioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Formulario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComprobacionCamposAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cComprobacionCamposComprobacionCamposKeyword_0_0 = (Keyword)cComprobacionCamposAssignment_0.eContents().get(0);
		private final Assignment cComprobacionAccionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cComprobacionAccionComprobacionAccionKeyword_1_0 = (Keyword)cComprobacionAccionAssignment_1.eContents().get(0);
		private final Keyword cFormularioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLayoutKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLayoutAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLayoutLayoutParserRuleCall_6_0 = (RuleCall)cLayoutAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPruebasKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPruebasAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPruebasPruebaInterfazParserRuleCall_7_1_0 = (RuleCall)cPruebasAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Formulario:
		//	comprobacionCampos?="comprobacionCampos"? comprobacionAccion?="comprobacionAccion"? "Formulario" name=EString "{"
		//	"layout" layout=Layout ("pruebas" pruebas=PruebaInterfaz)? "}";
		@Override public ParserRule getRule() { return rule; }

		//comprobacionCampos?="comprobacionCampos"? comprobacionAccion?="comprobacionAccion"? "Formulario" name=EString "{"
		//"layout" layout=Layout ("pruebas" pruebas=PruebaInterfaz)? "}"
		public Group getGroup() { return cGroup; }

		//comprobacionCampos?="comprobacionCampos"?
		public Assignment getComprobacionCamposAssignment_0() { return cComprobacionCamposAssignment_0; }

		//"comprobacionCampos"
		public Keyword getComprobacionCamposComprobacionCamposKeyword_0_0() { return cComprobacionCamposComprobacionCamposKeyword_0_0; }

		//comprobacionAccion?="comprobacionAccion"?
		public Assignment getComprobacionAccionAssignment_1() { return cComprobacionAccionAssignment_1; }

		//"comprobacionAccion"
		public Keyword getComprobacionAccionComprobacionAccionKeyword_1_0() { return cComprobacionAccionComprobacionAccionKeyword_1_0; }

		//"Formulario"
		public Keyword getFormularioKeyword_2() { return cFormularioKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"layout"
		public Keyword getLayoutKeyword_5() { return cLayoutKeyword_5; }

		//layout=Layout
		public Assignment getLayoutAssignment_6() { return cLayoutAssignment_6; }

		//Layout
		public RuleCall getLayoutLayoutParserRuleCall_6_0() { return cLayoutLayoutParserRuleCall_6_0; }

		//("pruebas" pruebas=PruebaInterfaz)?
		public Group getGroup_7() { return cGroup_7; }

		//"pruebas"
		public Keyword getPruebasKeyword_7_0() { return cPruebasKeyword_7_0; }

		//pruebas=PruebaInterfaz
		public Assignment getPruebasAssignment_7_1() { return cPruebasAssignment_7_1; }

		//PruebaInterfaz
		public RuleCall getPruebasPruebaInterfazParserRuleCall_7_1_0() { return cPruebasPruebaInterfazParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class InputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Input");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInputTextoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInputRadioParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInputComboParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cInputCheckParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cBotonValidarParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cBotonGuardar_ImplParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cBotonCancelarParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cBotonCustomParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Input:
		//	InputTexto | InputRadio | InputCombo | InputCheck | BotonValidar | BotonGuardar_Impl | BotonCancelar | BotonCustom;
		@Override public ParserRule getRule() { return rule; }

		//InputTexto | InputRadio | InputCombo | InputCheck | BotonValidar | BotonGuardar_Impl | BotonCancelar | BotonCustom
		public Alternatives getAlternatives() { return cAlternatives; }

		//InputTexto
		public RuleCall getInputTextoParserRuleCall_0() { return cInputTextoParserRuleCall_0; }

		//InputRadio
		public RuleCall getInputRadioParserRuleCall_1() { return cInputRadioParserRuleCall_1; }

		//InputCombo
		public RuleCall getInputComboParserRuleCall_2() { return cInputComboParserRuleCall_2; }

		//InputCheck
		public RuleCall getInputCheckParserRuleCall_3() { return cInputCheckParserRuleCall_3; }

		//BotonValidar
		public RuleCall getBotonValidarParserRuleCall_4() { return cBotonValidarParserRuleCall_4; }

		//BotonGuardar_Impl
		public RuleCall getBotonGuardar_ImplParserRuleCall_5() { return cBotonGuardar_ImplParserRuleCall_5; }

		//BotonCancelar
		public RuleCall getBotonCancelarParserRuleCall_6() { return cBotonCancelarParserRuleCall_6; }

		//BotonCustom
		public RuleCall getBotonCustomParserRuleCall_7() { return cBotonCustomParserRuleCall_7; }
	}

	public class AccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Accion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAccionValorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAccionSeleccionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAccionPulsacionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Accion:
		//	AccionValor | AccionSeleccion | AccionPulsacion;
		@Override public ParserRule getRule() { return rule; }

		//AccionValor | AccionSeleccion | AccionPulsacion
		public Alternatives getAlternatives() { return cAlternatives; }

		//AccionValor
		public RuleCall getAccionValorParserRuleCall_0() { return cAccionValorParserRuleCall_0; }

		//AccionSeleccion
		public RuleCall getAccionSeleccionParserRuleCall_1() { return cAccionSeleccionParserRuleCall_1; }

		//AccionPulsacion
		public RuleCall getAccionPulsacionParserRuleCall_2() { return cAccionPulsacionParserRuleCall_2; }
	}

	public class ReaccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Reaccion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cReaccionVisibleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cReaccionHabilitadoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Reaccion:
		//	ReaccionVisible | ReaccionHabilitado;
		@Override public ParserRule getRule() { return rule; }

		//ReaccionVisible | ReaccionHabilitado
		public Alternatives getAlternatives() { return cAlternatives; }

		//ReaccionVisible
		public RuleCall getReaccionVisibleParserRuleCall_0() { return cReaccionVisibleParserRuleCall_0; }

		//ReaccionHabilitado
		public RuleCall getReaccionHabilitadoParserRuleCall_1() { return cReaccionHabilitadoParserRuleCall_1; }
	}

	public class AsercionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Asercion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAsercionInvisibleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAsercionHabilitadoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAsercionValorParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAsercionSeleccionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Asercion:
		//	AsercionInvisible | AsercionHabilitado | AsercionValor | AsercionSeleccion;
		@Override public ParserRule getRule() { return rule; }

		//AsercionInvisible | AsercionHabilitado | AsercionValor | AsercionSeleccion
		public Alternatives getAlternatives() { return cAlternatives; }

		//AsercionInvisible
		public RuleCall getAsercionInvisibleParserRuleCall_0() { return cAsercionInvisibleParserRuleCall_0; }

		//AsercionHabilitado
		public RuleCall getAsercionHabilitadoParserRuleCall_1() { return cAsercionHabilitadoParserRuleCall_1; }

		//AsercionValor
		public RuleCall getAsercionValorParserRuleCall_2() { return cAsercionValorParserRuleCall_2; }

		//AsercionSeleccion
		public RuleCall getAsercionSeleccionParserRuleCall_3() { return cAsercionSeleccionParserRuleCall_3; }
	}

	public class LayoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Layout");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLayoutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColumnasKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColumnasEIntParserRuleCall_3_0 = (RuleCall)cColumnasAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEntradasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEntradasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEntradasInputParserRuleCall_4_2_0 = (RuleCall)cEntradasAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEntradasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEntradasInputParserRuleCall_4_3_1_0 = (RuleCall)cEntradasAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Layout:
		//	"Layout" "{" "columnas" columnas=EInt ("entradas" "{" entradas+=Input ("," entradas+=Input)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"Layout" "{" "columnas" columnas=EInt ("entradas" "{" entradas+=Input ("," entradas+=Input)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Layout"
		public Keyword getLayoutKeyword_0() { return cLayoutKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"columnas"
		public Keyword getColumnasKeyword_2() { return cColumnasKeyword_2; }

		//columnas=EInt
		public Assignment getColumnasAssignment_3() { return cColumnasAssignment_3; }

		//EInt
		public RuleCall getColumnasEIntParserRuleCall_3_0() { return cColumnasEIntParserRuleCall_3_0; }

		//("entradas" "{" entradas+=Input ("," entradas+=Input)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"entradas"
		public Keyword getEntradasKeyword_4_0() { return cEntradasKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//entradas+=Input
		public Assignment getEntradasAssignment_4_2() { return cEntradasAssignment_4_2; }

		//Input
		public RuleCall getEntradasInputParserRuleCall_4_2_0() { return cEntradasInputParserRuleCall_4_2_0; }

		//("," entradas+=Input)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//entradas+=Input
		public Assignment getEntradasAssignment_4_3_1() { return cEntradasAssignment_4_3_1; }

		//Input
		public RuleCall getEntradasInputParserRuleCall_4_3_1_0() { return cEntradasInputParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class PruebaInterfazElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PruebaInterfaz");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPruebaInterfazAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPruebaInterfazKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAccionesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAccionesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAccionesAccionParserRuleCall_4_2_0 = (RuleCall)cAccionesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAccionesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAccionesAccionParserRuleCall_4_3_1_0 = (RuleCall)cAccionesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//PruebaInterfaz:
		//	{PruebaInterfaz} "PruebaInterfaz" name=EString "{" ("acciones" "{" acciones+=Accion ("," acciones+=Accion)* "}")?
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//{PruebaInterfaz} "PruebaInterfaz" name=EString "{" ("acciones" "{" acciones+=Accion ("," acciones+=Accion)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{PruebaInterfaz}
		public Action getPruebaInterfazAction_0() { return cPruebaInterfazAction_0; }

		//"PruebaInterfaz"
		public Keyword getPruebaInterfazKeyword_1() { return cPruebaInterfazKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("acciones" "{" acciones+=Accion ("," acciones+=Accion)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"acciones"
		public Keyword getAccionesKeyword_4_0() { return cAccionesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//acciones+=Accion
		public Assignment getAccionesAssignment_4_2() { return cAccionesAssignment_4_2; }

		//Accion
		public RuleCall getAccionesAccionParserRuleCall_4_2_0() { return cAccionesAccionParserRuleCall_4_2_0; }

		//("," acciones+=Accion)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//acciones+=Accion
		public Assignment getAccionesAssignment_4_3_1() { return cAccionesAssignment_4_3_1; }

		//Accion
		public RuleCall getAccionesAccionParserRuleCall_4_3_1_0() { return cAccionesAccionParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		@Override public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class InputTextoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputTexto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInputTextoAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVisibleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVisibleVisibleKeyword_1_0 = (Keyword)cVisibleAssignment_1.eContents().get(0);
		private final Assignment cHabilitadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHabilitadoHabilitadoKeyword_2_0 = (Keyword)cHabilitadoAssignment_2.eContents().get(0);
		private final Assignment cObligatorioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cObligatorioObligatorioKeyword_3_0 = (Keyword)cObligatorioAssignment_3.eContents().get(0);
		private final Keyword cInputTextoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameEStringParserRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cValorKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cValorAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cValorEStringParserRuleCall_7_1_0 = (RuleCall)cValorAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//InputTexto:
		//	{InputTexto} visible?="visible"? habilitado?="habilitado"? obligatorio?="obligatorio"? "InputTexto" name=EString "{"
		//	("valor" valor=EString)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{InputTexto} visible?="visible"? habilitado?="habilitado"? obligatorio?="obligatorio"? "InputTexto" name=EString "{"
		//("valor" valor=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{InputTexto}
		public Action getInputTextoAction_0() { return cInputTextoAction_0; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_1() { return cVisibleAssignment_1; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_1_0() { return cVisibleVisibleKeyword_1_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_2() { return cHabilitadoAssignment_2; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_2_0() { return cHabilitadoHabilitadoKeyword_2_0; }

		//obligatorio?="obligatorio"?
		public Assignment getObligatorioAssignment_3() { return cObligatorioAssignment_3; }

		//"obligatorio"
		public Keyword getObligatorioObligatorioKeyword_3_0() { return cObligatorioObligatorioKeyword_3_0; }

		//"InputTexto"
		public Keyword getInputTextoKeyword_4() { return cInputTextoKeyword_4; }

		//name=EString
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }

		//EString
		public RuleCall getNameEStringParserRuleCall_5_0() { return cNameEStringParserRuleCall_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//("valor" valor=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"valor"
		public Keyword getValorKeyword_7_0() { return cValorKeyword_7_0; }

		//valor=EString
		public Assignment getValorAssignment_7_1() { return cValorAssignment_7_1; }

		//EString
		public RuleCall getValorEStringParserRuleCall_7_1_0() { return cValorEStringParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class InputRadioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputRadio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleAssignment_0.eContents().get(0);
		private final Assignment cHabilitadoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHabilitadoHabilitadoKeyword_1_0 = (Keyword)cHabilitadoAssignment_1.eContents().get(0);
		private final Keyword cInputRadioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValoresKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cValoresAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cValoresEStringParserRuleCall_5_2_0 = (RuleCall)cValoresAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cValoresAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cValoresEStringParserRuleCall_5_3_1_0 = (RuleCall)cValoresAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSeleccionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSeleccionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSeleccionEIntParserRuleCall_6_1_0 = (RuleCall)cSeleccionAssignment_6_1.eContents().get(0);
		private final Keyword cReaccionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReaccionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cReaccionReaccionParserRuleCall_8_0 = (RuleCall)cReaccionAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//InputRadio:
		//	visible?="visible"? habilitado?="habilitado"? "InputRadio" name=EString "{" ("valores" "{" valores+=EString (","
		//	valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "reaccion" reaccion=Reaccion "}";
		@Override public ParserRule getRule() { return rule; }

		//visible?="visible"? habilitado?="habilitado"? "InputRadio" name=EString "{" ("valores" "{" valores+=EString (","
		//valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "reaccion" reaccion=Reaccion "}"
		public Group getGroup() { return cGroup; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_0() { return cVisibleAssignment_0; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_1() { return cHabilitadoAssignment_1; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_1_0() { return cHabilitadoHabilitadoKeyword_1_0; }

		//"InputRadio"
		public Keyword getInputRadioKeyword_2() { return cInputRadioKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("valores" "{" valores+=EString ("," valores+=EString)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"valores"
		public Keyword getValoresKeyword_5_0() { return cValoresKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//valores+=EString
		public Assignment getValoresAssignment_5_2() { return cValoresAssignment_5_2; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_5_2_0() { return cValoresEStringParserRuleCall_5_2_0; }

		//("," valores+=EString)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//valores+=EString
		public Assignment getValoresAssignment_5_3_1() { return cValoresAssignment_5_3_1; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_5_3_1_0() { return cValoresEStringParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("seleccion" seleccion=EInt)?
		public Group getGroup_6() { return cGroup_6; }

		//"seleccion"
		public Keyword getSeleccionKeyword_6_0() { return cSeleccionKeyword_6_0; }

		//seleccion=EInt
		public Assignment getSeleccionAssignment_6_1() { return cSeleccionAssignment_6_1; }

		//EInt
		public RuleCall getSeleccionEIntParserRuleCall_6_1_0() { return cSeleccionEIntParserRuleCall_6_1_0; }

		//"reaccion"
		public Keyword getReaccionKeyword_7() { return cReaccionKeyword_7; }

		//reaccion=Reaccion
		public Assignment getReaccionAssignment_8() { return cReaccionAssignment_8; }

		//Reaccion
		public RuleCall getReaccionReaccionParserRuleCall_8_0() { return cReaccionReaccionParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class InputComboElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputCombo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInputComboAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVisibleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVisibleVisibleKeyword_1_0 = (Keyword)cVisibleAssignment_1.eContents().get(0);
		private final Assignment cHabilitadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHabilitadoHabilitadoKeyword_2_0 = (Keyword)cHabilitadoAssignment_2.eContents().get(0);
		private final Keyword cInputComboKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cValoresKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cValoresAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cValoresEStringParserRuleCall_6_2_0 = (RuleCall)cValoresAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cValoresAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cValoresEStringParserRuleCall_6_3_1_0 = (RuleCall)cValoresAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSeleccionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSeleccionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSeleccionEIntParserRuleCall_7_1_0 = (RuleCall)cSeleccionAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//InputCombo:
		//	{InputCombo} visible?="visible"? habilitado?="habilitado"? "InputCombo" name=EString "{" ("valores" "{"
		//	valores+=EString ("," valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{InputCombo} visible?="visible"? habilitado?="habilitado"? "InputCombo" name=EString "{" ("valores" "{" valores+=EString
		//("," valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{InputCombo}
		public Action getInputComboAction_0() { return cInputComboAction_0; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_1() { return cVisibleAssignment_1; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_1_0() { return cVisibleVisibleKeyword_1_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_2() { return cHabilitadoAssignment_2; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_2_0() { return cHabilitadoHabilitadoKeyword_2_0; }

		//"InputCombo"
		public Keyword getInputComboKeyword_3() { return cInputComboKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//("valores" "{" valores+=EString ("," valores+=EString)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"valores"
		public Keyword getValoresKeyword_6_0() { return cValoresKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//valores+=EString
		public Assignment getValoresAssignment_6_2() { return cValoresAssignment_6_2; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_6_2_0() { return cValoresEStringParserRuleCall_6_2_0; }

		//("," valores+=EString)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//valores+=EString
		public Assignment getValoresAssignment_6_3_1() { return cValoresAssignment_6_3_1; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_6_3_1_0() { return cValoresEStringParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//("seleccion" seleccion=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"seleccion"
		public Keyword getSeleccionKeyword_7_0() { return cSeleccionKeyword_7_0; }

		//seleccion=EInt
		public Assignment getSeleccionAssignment_7_1() { return cSeleccionAssignment_7_1; }

		//EInt
		public RuleCall getSeleccionEIntParserRuleCall_7_1_0() { return cSeleccionEIntParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class InputCheckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputCheck");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleAssignment_0.eContents().get(0);
		private final Assignment cHabilitadoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHabilitadoHabilitadoKeyword_1_0 = (Keyword)cHabilitadoAssignment_1.eContents().get(0);
		private final Keyword cInputCheckKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValoresKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cValoresAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cValoresEStringParserRuleCall_5_2_0 = (RuleCall)cValoresAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cValoresAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cValoresEStringParserRuleCall_5_3_1_0 = (RuleCall)cValoresAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSeleccionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cSeleccionAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cSeleccionEIntParserRuleCall_6_2_0 = (RuleCall)cSeleccionAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cSeleccionAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cSeleccionEIntParserRuleCall_6_3_1_0 = (RuleCall)cSeleccionAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cReaccionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReaccionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cReaccionReaccionParserRuleCall_8_0 = (RuleCall)cReaccionAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//InputCheck:
		//	visible?="visible"? habilitado?="habilitado"? "InputCheck" name=EString "{" ("valores" "{" valores+=EString (","
		//	valores+=EString)* "}")? ("seleccion" "{" seleccion+=EInt ("," seleccion+=EInt)* "}")? "reaccion" reaccion=Reaccion
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//visible?="visible"? habilitado?="habilitado"? "InputCheck" name=EString "{" ("valores" "{" valores+=EString (","
		//valores+=EString)* "}")? ("seleccion" "{" seleccion+=EInt ("," seleccion+=EInt)* "}")? "reaccion" reaccion=Reaccion
		//"}"
		public Group getGroup() { return cGroup; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_0() { return cVisibleAssignment_0; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_1() { return cHabilitadoAssignment_1; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_1_0() { return cHabilitadoHabilitadoKeyword_1_0; }

		//"InputCheck"
		public Keyword getInputCheckKeyword_2() { return cInputCheckKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("valores" "{" valores+=EString ("," valores+=EString)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"valores"
		public Keyword getValoresKeyword_5_0() { return cValoresKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//valores+=EString
		public Assignment getValoresAssignment_5_2() { return cValoresAssignment_5_2; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_5_2_0() { return cValoresEStringParserRuleCall_5_2_0; }

		//("," valores+=EString)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//valores+=EString
		public Assignment getValoresAssignment_5_3_1() { return cValoresAssignment_5_3_1; }

		//EString
		public RuleCall getValoresEStringParserRuleCall_5_3_1_0() { return cValoresEStringParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("seleccion" "{" seleccion+=EInt ("," seleccion+=EInt)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"seleccion"
		public Keyword getSeleccionKeyword_6_0() { return cSeleccionKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//seleccion+=EInt
		public Assignment getSeleccionAssignment_6_2() { return cSeleccionAssignment_6_2; }

		//EInt
		public RuleCall getSeleccionEIntParserRuleCall_6_2_0() { return cSeleccionEIntParserRuleCall_6_2_0; }

		//("," seleccion+=EInt)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//seleccion+=EInt
		public Assignment getSeleccionAssignment_6_3_1() { return cSeleccionAssignment_6_3_1; }

		//EInt
		public RuleCall getSeleccionEIntParserRuleCall_6_3_1_0() { return cSeleccionEIntParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"reaccion"
		public Keyword getReaccionKeyword_7() { return cReaccionKeyword_7; }

		//reaccion=Reaccion
		public Assignment getReaccionAssignment_8() { return cReaccionAssignment_8; }

		//Reaccion
		public RuleCall getReaccionReaccionParserRuleCall_8_0() { return cReaccionReaccionParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class BotonValidarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BotonValidar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBotonValidarAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVisibleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVisibleVisibleKeyword_1_0 = (Keyword)cVisibleAssignment_1.eContents().get(0);
		private final Assignment cHabilitadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHabilitadoHabilitadoKeyword_2_0 = (Keyword)cHabilitadoAssignment_2.eContents().get(0);
		private final Keyword cBotonValidarKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//BotonValidar:
		//	{BotonValidar} visible?="visible"? habilitado?="habilitado"? "BotonValidar" name=EString;
		@Override public ParserRule getRule() { return rule; }

		//{BotonValidar} visible?="visible"? habilitado?="habilitado"? "BotonValidar" name=EString
		public Group getGroup() { return cGroup; }

		//{BotonValidar}
		public Action getBotonValidarAction_0() { return cBotonValidarAction_0; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_1() { return cVisibleAssignment_1; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_1_0() { return cVisibleVisibleKeyword_1_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_2() { return cHabilitadoAssignment_2; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_2_0() { return cHabilitadoHabilitadoKeyword_2_0; }

		//"BotonValidar"
		public Keyword getBotonValidarKeyword_3() { return cBotonValidarKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
	}

	public class BotonGuardar_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BotonGuardar_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBotonGuardarAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVisibleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVisibleVisibleKeyword_1_0 = (Keyword)cVisibleAssignment_1.eContents().get(0);
		private final Assignment cHabilitadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHabilitadoHabilitadoKeyword_2_0 = (Keyword)cHabilitadoAssignment_2.eContents().get(0);
		private final Keyword cBotonGuardarKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//BotonGuardar_Impl returns BotonGuardar:
		//	{BotonGuardar} visible?="visible"? habilitado?="habilitado"? "BotonGuardar" name=EString;
		@Override public ParserRule getRule() { return rule; }

		//{BotonGuardar} visible?="visible"? habilitado?="habilitado"? "BotonGuardar" name=EString
		public Group getGroup() { return cGroup; }

		//{BotonGuardar}
		public Action getBotonGuardarAction_0() { return cBotonGuardarAction_0; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_1() { return cVisibleAssignment_1; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_1_0() { return cVisibleVisibleKeyword_1_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_2() { return cHabilitadoAssignment_2; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_2_0() { return cHabilitadoHabilitadoKeyword_2_0; }

		//"BotonGuardar"
		public Keyword getBotonGuardarKeyword_3() { return cBotonGuardarKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
	}

	public class BotonCancelarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BotonCancelar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBotonCancelarAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVisibleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVisibleVisibleKeyword_1_0 = (Keyword)cVisibleAssignment_1.eContents().get(0);
		private final Assignment cHabilitadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHabilitadoHabilitadoKeyword_2_0 = (Keyword)cHabilitadoAssignment_2.eContents().get(0);
		private final Keyword cBotonCancelarKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//BotonCancelar:
		//	{BotonCancelar} visible?="visible"? habilitado?="habilitado"? "BotonCancelar" name=EString;
		@Override public ParserRule getRule() { return rule; }

		//{BotonCancelar} visible?="visible"? habilitado?="habilitado"? "BotonCancelar" name=EString
		public Group getGroup() { return cGroup; }

		//{BotonCancelar}
		public Action getBotonCancelarAction_0() { return cBotonCancelarAction_0; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_1() { return cVisibleAssignment_1; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_1_0() { return cVisibleVisibleKeyword_1_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_2() { return cHabilitadoAssignment_2; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_2_0() { return cHabilitadoHabilitadoKeyword_2_0; }

		//"BotonCancelar"
		public Keyword getBotonCancelarKeyword_3() { return cBotonCancelarKeyword_3; }

		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
	}

	public class BotonCustomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BotonCustom");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVisibleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleAssignment_0.eContents().get(0);
		private final Assignment cHabilitadoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHabilitadoHabilitadoKeyword_1_0 = (Keyword)cHabilitadoAssignment_1.eContents().get(0);
		private final Keyword cBotonCustomKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFuncionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFuncionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFuncionEStringParserRuleCall_6_0 = (RuleCall)cFuncionAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//BotonCustom:
		//	visible?="visible"? habilitado?="habilitado"? "BotonCustom" name=EString "{" "funcion" funcion=EString "}";
		@Override public ParserRule getRule() { return rule; }

		//visible?="visible"? habilitado?="habilitado"? "BotonCustom" name=EString "{" "funcion" funcion=EString "}"
		public Group getGroup() { return cGroup; }

		//visible?="visible"?
		public Assignment getVisibleAssignment_0() { return cVisibleAssignment_0; }

		//"visible"
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }

		//habilitado?="habilitado"?
		public Assignment getHabilitadoAssignment_1() { return cHabilitadoAssignment_1; }

		//"habilitado"
		public Keyword getHabilitadoHabilitadoKeyword_1_0() { return cHabilitadoHabilitadoKeyword_1_0; }

		//"BotonCustom"
		public Keyword getBotonCustomKeyword_2() { return cBotonCustomKeyword_2; }

		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"funcion"
		public Keyword getFuncionKeyword_5() { return cFuncionKeyword_5; }

		//funcion=EString
		public Assignment getFuncionAssignment_6() { return cFuncionAssignment_6; }

		//EString
		public RuleCall getFuncionEStringParserRuleCall_6_0() { return cFuncionEStringParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ReaccionVisibleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReaccionVisible");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReaccionVisibleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cActivacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActivacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActivacionEIntParserRuleCall_3_0 = (RuleCall)cActivacionAssignment_3.eContents().get(0);
		private final Keyword cObjetivoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cObjetivoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cObjetivoInputCrossReference_5_0 = (CrossReference)cObjetivoAssignment_5.eContents().get(0);
		private final RuleCall cObjetivoInputEStringParserRuleCall_5_0_1 = (RuleCall)cObjetivoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ReaccionVisible:
		//	"ReaccionVisible" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"ReaccionVisible" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//"ReaccionVisible"
		public Keyword getReaccionVisibleKeyword_0() { return cReaccionVisibleKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"activacion"
		public Keyword getActivacionKeyword_2() { return cActivacionKeyword_2; }

		//activacion=EInt
		public Assignment getActivacionAssignment_3() { return cActivacionAssignment_3; }

		//EInt
		public RuleCall getActivacionEIntParserRuleCall_3_0() { return cActivacionEIntParserRuleCall_3_0; }

		//"objetivo"
		public Keyword getObjetivoKeyword_4() { return cObjetivoKeyword_4; }

		//objetivo=[Input|EString]
		public Assignment getObjetivoAssignment_5() { return cObjetivoAssignment_5; }

		//[Input|EString]
		public CrossReference getObjetivoInputCrossReference_5_0() { return cObjetivoInputCrossReference_5_0; }

		//EString
		public RuleCall getObjetivoInputEStringParserRuleCall_5_0_1() { return cObjetivoInputEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ReaccionHabilitadoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReaccionHabilitado");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReaccionHabilitadoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cActivacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActivacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActivacionEIntParserRuleCall_3_0 = (RuleCall)cActivacionAssignment_3.eContents().get(0);
		private final Keyword cObjetivoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cObjetivoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cObjetivoInputCrossReference_5_0 = (CrossReference)cObjetivoAssignment_5.eContents().get(0);
		private final RuleCall cObjetivoInputEStringParserRuleCall_5_0_1 = (RuleCall)cObjetivoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ReaccionHabilitado:
		//	"ReaccionHabilitado" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"ReaccionHabilitado" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//"ReaccionHabilitado"
		public Keyword getReaccionHabilitadoKeyword_0() { return cReaccionHabilitadoKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"activacion"
		public Keyword getActivacionKeyword_2() { return cActivacionKeyword_2; }

		//activacion=EInt
		public Assignment getActivacionAssignment_3() { return cActivacionAssignment_3; }

		//EInt
		public RuleCall getActivacionEIntParserRuleCall_3_0() { return cActivacionEIntParserRuleCall_3_0; }

		//"objetivo"
		public Keyword getObjetivoKeyword_4() { return cObjetivoKeyword_4; }

		//objetivo=[Input|EString]
		public Assignment getObjetivoAssignment_5() { return cObjetivoAssignment_5; }

		//[Input|EString]
		public CrossReference getObjetivoInputCrossReference_5_0() { return cObjetivoInputCrossReference_5_0; }

		//EString
		public RuleCall getObjetivoInputEStringParserRuleCall_5_0_1() { return cObjetivoInputEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class AccionValorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AccionValor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAccionValorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValorEStringParserRuleCall_3_0 = (RuleCall)cValorAssignment_3.eContents().get(0);
		private final Keyword cElementoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElementoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cElementoInputCrossReference_5_0 = (CrossReference)cElementoAssignment_5.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_5_0_1 = (RuleCall)cElementoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cAsercionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAsercionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAsercionAsercionParserRuleCall_7_0 = (RuleCall)cAsercionAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//AccionValor:
		//	"AccionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
		@Override public ParserRule getRule() { return rule; }

		//"AccionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}"
		public Group getGroup() { return cGroup; }

		//"AccionValor"
		public Keyword getAccionValorKeyword_0() { return cAccionValorKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"valor"
		public Keyword getValorKeyword_2() { return cValorKeyword_2; }

		//valor=EString
		public Assignment getValorAssignment_3() { return cValorAssignment_3; }

		//EString
		public RuleCall getValorEStringParserRuleCall_3_0() { return cValorEStringParserRuleCall_3_0; }

		//"elemento"
		public Keyword getElementoKeyword_4() { return cElementoKeyword_4; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_5() { return cElementoAssignment_5; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_5_0() { return cElementoInputCrossReference_5_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_5_0_1() { return cElementoInputEStringParserRuleCall_5_0_1; }

		//"asercion"
		public Keyword getAsercionKeyword_6() { return cAsercionKeyword_6; }

		//asercion=Asercion
		public Assignment getAsercionAssignment_7() { return cAsercionAssignment_7; }

		//Asercion
		public RuleCall getAsercionAsercionParserRuleCall_7_0() { return cAsercionAsercionParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class AccionSeleccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AccionSeleccion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAccionSeleccionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValorEIntParserRuleCall_3_0 = (RuleCall)cValorAssignment_3.eContents().get(0);
		private final Keyword cElementoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElementoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cElementoInputCrossReference_5_0 = (CrossReference)cElementoAssignment_5.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_5_0_1 = (RuleCall)cElementoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cAsercionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAsercionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAsercionAsercionParserRuleCall_7_0 = (RuleCall)cAsercionAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//AccionSeleccion:
		//	"AccionSeleccion" "{" "valor" valor=EInt "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
		@Override public ParserRule getRule() { return rule; }

		//"AccionSeleccion" "{" "valor" valor=EInt "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}"
		public Group getGroup() { return cGroup; }

		//"AccionSeleccion"
		public Keyword getAccionSeleccionKeyword_0() { return cAccionSeleccionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"valor"
		public Keyword getValorKeyword_2() { return cValorKeyword_2; }

		//valor=EInt
		public Assignment getValorAssignment_3() { return cValorAssignment_3; }

		//EInt
		public RuleCall getValorEIntParserRuleCall_3_0() { return cValorEIntParserRuleCall_3_0; }

		//"elemento"
		public Keyword getElementoKeyword_4() { return cElementoKeyword_4; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_5() { return cElementoAssignment_5; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_5_0() { return cElementoInputCrossReference_5_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_5_0_1() { return cElementoInputEStringParserRuleCall_5_0_1; }

		//"asercion"
		public Keyword getAsercionKeyword_6() { return cAsercionKeyword_6; }

		//asercion=Asercion
		public Assignment getAsercionAssignment_7() { return cAsercionAssignment_7; }

		//Asercion
		public RuleCall getAsercionAsercionParserRuleCall_7_0() { return cAsercionAsercionParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class AccionPulsacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AccionPulsacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAccionPulsacionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cElementoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElementoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cElementoInputCrossReference_3_0 = (CrossReference)cElementoAssignment_3.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_3_0_1 = (RuleCall)cElementoInputCrossReference_3_0.eContents().get(1);
		private final Keyword cAsercionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAsercionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAsercionAsercionParserRuleCall_5_0 = (RuleCall)cAsercionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//AccionPulsacion:
		//	"AccionPulsacion" "{" "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
		@Override public ParserRule getRule() { return rule; }

		//"AccionPulsacion" "{" "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}"
		public Group getGroup() { return cGroup; }

		//"AccionPulsacion"
		public Keyword getAccionPulsacionKeyword_0() { return cAccionPulsacionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"elemento"
		public Keyword getElementoKeyword_2() { return cElementoKeyword_2; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_3() { return cElementoAssignment_3; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_3_0() { return cElementoInputCrossReference_3_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_3_0_1() { return cElementoInputEStringParserRuleCall_3_0_1; }

		//"asercion"
		public Keyword getAsercionKeyword_4() { return cAsercionKeyword_4; }

		//asercion=Asercion
		public Assignment getAsercionAssignment_5() { return cAsercionAssignment_5; }

		//Asercion
		public RuleCall getAsercionAsercionParserRuleCall_5_0() { return cAsercionAsercionParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class AsercionInvisibleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AsercionInvisible");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEstadoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cEstadoEstadoKeyword_0_0 = (Keyword)cEstadoAssignment_0.eContents().get(0);
		private final Keyword cAsercionInvisibleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cElementoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cElementoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cElementoInputCrossReference_4_0 = (CrossReference)cElementoAssignment_4.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_4_0_1 = (RuleCall)cElementoInputCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//AsercionInvisible:
		//	estado?="estado" "AsercionInvisible" "{" "elemento" elemento=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//estado?="estado" "AsercionInvisible" "{" "elemento" elemento=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//estado?="estado"
		public Assignment getEstadoAssignment_0() { return cEstadoAssignment_0; }

		//"estado"
		public Keyword getEstadoEstadoKeyword_0_0() { return cEstadoEstadoKeyword_0_0; }

		//"AsercionInvisible"
		public Keyword getAsercionInvisibleKeyword_1() { return cAsercionInvisibleKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"elemento"
		public Keyword getElementoKeyword_3() { return cElementoKeyword_3; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_4() { return cElementoAssignment_4; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_4_0() { return cElementoInputCrossReference_4_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_4_0_1() { return cElementoInputEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class AsercionHabilitadoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AsercionHabilitado");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEstadoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cEstadoEstadoKeyword_0_0 = (Keyword)cEstadoAssignment_0.eContents().get(0);
		private final Keyword cAsercionHabilitadoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cElementoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cElementoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cElementoInputCrossReference_4_0 = (CrossReference)cElementoAssignment_4.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_4_0_1 = (RuleCall)cElementoInputCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//AsercionHabilitado:
		//	estado?="estado" "AsercionHabilitado" "{" "elemento" elemento=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//estado?="estado" "AsercionHabilitado" "{" "elemento" elemento=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//estado?="estado"
		public Assignment getEstadoAssignment_0() { return cEstadoAssignment_0; }

		//"estado"
		public Keyword getEstadoEstadoKeyword_0_0() { return cEstadoEstadoKeyword_0_0; }

		//"AsercionHabilitado"
		public Keyword getAsercionHabilitadoKeyword_1() { return cAsercionHabilitadoKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"elemento"
		public Keyword getElementoKeyword_3() { return cElementoKeyword_3; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_4() { return cElementoAssignment_4; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_4_0() { return cElementoInputCrossReference_4_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_4_0_1() { return cElementoInputEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class AsercionValorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AsercionValor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsercionValorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValorEStringParserRuleCall_3_0 = (RuleCall)cValorAssignment_3.eContents().get(0);
		private final Keyword cElementoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElementoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cElementoInputCrossReference_5_0 = (CrossReference)cElementoAssignment_5.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_5_0_1 = (RuleCall)cElementoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//AsercionValor:
		//	"AsercionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"AsercionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//"AsercionValor"
		public Keyword getAsercionValorKeyword_0() { return cAsercionValorKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"valor"
		public Keyword getValorKeyword_2() { return cValorKeyword_2; }

		//valor=EString
		public Assignment getValorAssignment_3() { return cValorAssignment_3; }

		//EString
		public RuleCall getValorEStringParserRuleCall_3_0() { return cValorEStringParserRuleCall_3_0; }

		//"elemento"
		public Keyword getElementoKeyword_4() { return cElementoKeyword_4; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_5() { return cElementoAssignment_5; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_5_0() { return cElementoInputCrossReference_5_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_5_0_1() { return cElementoInputEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class AsercionSeleccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AsercionSeleccion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsercionSeleccionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEstadoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEstadoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEstadoEIntParserRuleCall_3_0 = (RuleCall)cEstadoAssignment_3.eContents().get(0);
		private final Keyword cElementoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElementoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cElementoInputCrossReference_5_0 = (CrossReference)cElementoAssignment_5.eContents().get(0);
		private final RuleCall cElementoInputEStringParserRuleCall_5_0_1 = (RuleCall)cElementoInputCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//AsercionSeleccion:
		//	"AsercionSeleccion" "{" "estado" estado=EInt "elemento" elemento=[Input|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"AsercionSeleccion" "{" "estado" estado=EInt "elemento" elemento=[Input|EString] "}"
		public Group getGroup() { return cGroup; }

		//"AsercionSeleccion"
		public Keyword getAsercionSeleccionKeyword_0() { return cAsercionSeleccionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"estado"
		public Keyword getEstadoKeyword_2() { return cEstadoKeyword_2; }

		//estado=EInt
		public Assignment getEstadoAssignment_3() { return cEstadoAssignment_3; }

		//EInt
		public RuleCall getEstadoEIntParserRuleCall_3_0() { return cEstadoEIntParserRuleCall_3_0; }

		//"elemento"
		public Keyword getElementoKeyword_4() { return cElementoKeyword_4; }

		//elemento=[Input|EString]
		public Assignment getElementoAssignment_5() { return cElementoAssignment_5; }

		//[Input|EString]
		public CrossReference getElementoInputCrossReference_5_0() { return cElementoInputCrossReference_5_0; }

		//EString
		public RuleCall getElementoInputEStringParserRuleCall_5_0_1() { return cElementoInputEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final FormularioElements pFormulario;
	private final InputElements pInput;
	private final AccionElements pAccion;
	private final ReaccionElements pReaccion;
	private final AsercionElements pAsercion;
	private final LayoutElements pLayout;
	private final EStringElements pEString;
	private final PruebaInterfazElements pPruebaInterfaz;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final InputTextoElements pInputTexto;
	private final InputRadioElements pInputRadio;
	private final InputComboElements pInputCombo;
	private final InputCheckElements pInputCheck;
	private final BotonValidarElements pBotonValidar;
	private final BotonGuardar_ImplElements pBotonGuardar_Impl;
	private final BotonCancelarElements pBotonCancelar;
	private final BotonCustomElements pBotonCustom;
	private final ReaccionVisibleElements pReaccionVisible;
	private final ReaccionHabilitadoElements pReaccionHabilitado;
	private final AccionValorElements pAccionValor;
	private final AccionSeleccionElements pAccionSeleccion;
	private final AccionPulsacionElements pAccionPulsacion;
	private final AsercionInvisibleElements pAsercionInvisible;
	private final AsercionHabilitadoElements pAsercionHabilitado;
	private final AsercionValorElements pAsercionValor;
	private final AsercionSeleccionElements pAsercionSeleccion;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public FormularioGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFormulario = new FormularioElements();
		this.pInput = new InputElements();
		this.pAccion = new AccionElements();
		this.pReaccion = new ReaccionElements();
		this.pAsercion = new AsercionElements();
		this.pLayout = new LayoutElements();
		this.pEString = new EStringElements();
		this.pPruebaInterfaz = new PruebaInterfazElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pInputTexto = new InputTextoElements();
		this.pInputRadio = new InputRadioElements();
		this.pInputCombo = new InputComboElements();
		this.pInputCheck = new InputCheckElements();
		this.pBotonValidar = new BotonValidarElements();
		this.pBotonGuardar_Impl = new BotonGuardar_ImplElements();
		this.pBotonCancelar = new BotonCancelarElements();
		this.pBotonCustom = new BotonCustomElements();
		this.pReaccionVisible = new ReaccionVisibleElements();
		this.pReaccionHabilitado = new ReaccionHabilitadoElements();
		this.pAccionValor = new AccionValorElements();
		this.pAccionSeleccion = new AccionSeleccionElements();
		this.pAccionPulsacion = new AccionPulsacionElements();
		this.pAsercionInvisible = new AsercionInvisibleElements();
		this.pAsercionHabilitado = new AsercionHabilitadoElements();
		this.pAsercionValor = new AsercionValorElements();
		this.pAsercionSeleccion = new AsercionSeleccionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("formulario.Formulario".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Formulario:
	//	comprobacionCampos?="comprobacionCampos"? comprobacionAccion?="comprobacionAccion"? "Formulario" name=EString "{"
	//	"layout" layout=Layout ("pruebas" pruebas=PruebaInterfaz)? "}";
	public FormularioElements getFormularioAccess() {
		return pFormulario;
	}
	
	public ParserRule getFormularioRule() {
		return getFormularioAccess().getRule();
	}

	//Input:
	//	InputTexto | InputRadio | InputCombo | InputCheck | BotonValidar | BotonGuardar_Impl | BotonCancelar | BotonCustom;
	public InputElements getInputAccess() {
		return pInput;
	}
	
	public ParserRule getInputRule() {
		return getInputAccess().getRule();
	}

	//Accion:
	//	AccionValor | AccionSeleccion | AccionPulsacion;
	public AccionElements getAccionAccess() {
		return pAccion;
	}
	
	public ParserRule getAccionRule() {
		return getAccionAccess().getRule();
	}

	//Reaccion:
	//	ReaccionVisible | ReaccionHabilitado;
	public ReaccionElements getReaccionAccess() {
		return pReaccion;
	}
	
	public ParserRule getReaccionRule() {
		return getReaccionAccess().getRule();
	}

	//Asercion:
	//	AsercionInvisible | AsercionHabilitado | AsercionValor | AsercionSeleccion;
	public AsercionElements getAsercionAccess() {
		return pAsercion;
	}
	
	public ParserRule getAsercionRule() {
		return getAsercionAccess().getRule();
	}

	//Layout:
	//	"Layout" "{" "columnas" columnas=EInt ("entradas" "{" entradas+=Input ("," entradas+=Input)* "}")? "}";
	public LayoutElements getLayoutAccess() {
		return pLayout;
	}
	
	public ParserRule getLayoutRule() {
		return getLayoutAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//PruebaInterfaz:
	//	{PruebaInterfaz} "PruebaInterfaz" name=EString "{" ("acciones" "{" acciones+=Accion ("," acciones+=Accion)* "}")?
	//	"}";
	public PruebaInterfazElements getPruebaInterfazAccess() {
		return pPruebaInterfaz;
	}
	
	public ParserRule getPruebaInterfazRule() {
		return getPruebaInterfazAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//InputTexto:
	//	{InputTexto} visible?="visible"? habilitado?="habilitado"? obligatorio?="obligatorio"? "InputTexto" name=EString "{"
	//	("valor" valor=EString)? "}";
	public InputTextoElements getInputTextoAccess() {
		return pInputTexto;
	}
	
	public ParserRule getInputTextoRule() {
		return getInputTextoAccess().getRule();
	}

	//InputRadio:
	//	visible?="visible"? habilitado?="habilitado"? "InputRadio" name=EString "{" ("valores" "{" valores+=EString (","
	//	valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "reaccion" reaccion=Reaccion "}";
	public InputRadioElements getInputRadioAccess() {
		return pInputRadio;
	}
	
	public ParserRule getInputRadioRule() {
		return getInputRadioAccess().getRule();
	}

	//InputCombo:
	//	{InputCombo} visible?="visible"? habilitado?="habilitado"? "InputCombo" name=EString "{" ("valores" "{"
	//	valores+=EString ("," valores+=EString)* "}")? ("seleccion" seleccion=EInt)? "}";
	public InputComboElements getInputComboAccess() {
		return pInputCombo;
	}
	
	public ParserRule getInputComboRule() {
		return getInputComboAccess().getRule();
	}

	//InputCheck:
	//	visible?="visible"? habilitado?="habilitado"? "InputCheck" name=EString "{" ("valores" "{" valores+=EString (","
	//	valores+=EString)* "}")? ("seleccion" "{" seleccion+=EInt ("," seleccion+=EInt)* "}")? "reaccion" reaccion=Reaccion
	//	"}";
	public InputCheckElements getInputCheckAccess() {
		return pInputCheck;
	}
	
	public ParserRule getInputCheckRule() {
		return getInputCheckAccess().getRule();
	}

	//BotonValidar:
	//	{BotonValidar} visible?="visible"? habilitado?="habilitado"? "BotonValidar" name=EString;
	public BotonValidarElements getBotonValidarAccess() {
		return pBotonValidar;
	}
	
	public ParserRule getBotonValidarRule() {
		return getBotonValidarAccess().getRule();
	}

	//BotonGuardar_Impl returns BotonGuardar:
	//	{BotonGuardar} visible?="visible"? habilitado?="habilitado"? "BotonGuardar" name=EString;
	public BotonGuardar_ImplElements getBotonGuardar_ImplAccess() {
		return pBotonGuardar_Impl;
	}
	
	public ParserRule getBotonGuardar_ImplRule() {
		return getBotonGuardar_ImplAccess().getRule();
	}

	//BotonCancelar:
	//	{BotonCancelar} visible?="visible"? habilitado?="habilitado"? "BotonCancelar" name=EString;
	public BotonCancelarElements getBotonCancelarAccess() {
		return pBotonCancelar;
	}
	
	public ParserRule getBotonCancelarRule() {
		return getBotonCancelarAccess().getRule();
	}

	//BotonCustom:
	//	visible?="visible"? habilitado?="habilitado"? "BotonCustom" name=EString "{" "funcion" funcion=EString "}";
	public BotonCustomElements getBotonCustomAccess() {
		return pBotonCustom;
	}
	
	public ParserRule getBotonCustomRule() {
		return getBotonCustomAccess().getRule();
	}

	//ReaccionVisible:
	//	"ReaccionVisible" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}";
	public ReaccionVisibleElements getReaccionVisibleAccess() {
		return pReaccionVisible;
	}
	
	public ParserRule getReaccionVisibleRule() {
		return getReaccionVisibleAccess().getRule();
	}

	//ReaccionHabilitado:
	//	"ReaccionHabilitado" "{" "activacion" activacion=EInt "objetivo" objetivo=[Input|EString] "}";
	public ReaccionHabilitadoElements getReaccionHabilitadoAccess() {
		return pReaccionHabilitado;
	}
	
	public ParserRule getReaccionHabilitadoRule() {
		return getReaccionHabilitadoAccess().getRule();
	}

	//AccionValor:
	//	"AccionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
	public AccionValorElements getAccionValorAccess() {
		return pAccionValor;
	}
	
	public ParserRule getAccionValorRule() {
		return getAccionValorAccess().getRule();
	}

	//AccionSeleccion:
	//	"AccionSeleccion" "{" "valor" valor=EInt "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
	public AccionSeleccionElements getAccionSeleccionAccess() {
		return pAccionSeleccion;
	}
	
	public ParserRule getAccionSeleccionRule() {
		return getAccionSeleccionAccess().getRule();
	}

	//AccionPulsacion:
	//	"AccionPulsacion" "{" "elemento" elemento=[Input|EString] "asercion" asercion=Asercion "}";
	public AccionPulsacionElements getAccionPulsacionAccess() {
		return pAccionPulsacion;
	}
	
	public ParserRule getAccionPulsacionRule() {
		return getAccionPulsacionAccess().getRule();
	}

	//AsercionInvisible:
	//	estado?="estado" "AsercionInvisible" "{" "elemento" elemento=[Input|EString] "}";
	public AsercionInvisibleElements getAsercionInvisibleAccess() {
		return pAsercionInvisible;
	}
	
	public ParserRule getAsercionInvisibleRule() {
		return getAsercionInvisibleAccess().getRule();
	}

	//AsercionHabilitado:
	//	estado?="estado" "AsercionHabilitado" "{" "elemento" elemento=[Input|EString] "}";
	public AsercionHabilitadoElements getAsercionHabilitadoAccess() {
		return pAsercionHabilitado;
	}
	
	public ParserRule getAsercionHabilitadoRule() {
		return getAsercionHabilitadoAccess().getRule();
	}

	//AsercionValor:
	//	"AsercionValor" "{" "valor" valor=EString "elemento" elemento=[Input|EString] "}";
	public AsercionValorElements getAsercionValorAccess() {
		return pAsercionValor;
	}
	
	public ParserRule getAsercionValorRule() {
		return getAsercionValorAccess().getRule();
	}

	//AsercionSeleccion:
	//	"AsercionSeleccion" "{" "estado" estado=EInt "elemento" elemento=[Input|EString] "}";
	public AsercionSeleccionElements getAsercionSeleccionAccess() {
		return pAsercionSeleccion;
	}
	
	public ParserRule getAsercionSeleccionRule() {
		return getAsercionSeleccionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
