/**
 * generated by Xtext
 */
package formulario.validation;

import formulario.validation.AbstractFormularioValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FormularioValidator extends AbstractFormularioValidator {
}
