/*
 * generated by Xtext
 */
package formulario.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import formulario.services.FormularioGrammarAccess;

public class FormularioParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FormularioGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected formulario.parser.antlr.internal.InternalFormularioParser createParser(XtextTokenStream stream) {
		return new formulario.parser.antlr.internal.InternalFormularioParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Formulario";
	}
	
	public FormularioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FormularioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
