/*
 * generated by Xtext
 */
package formulario;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FormularioUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return formulario.ui.internal.FormularioActivator.getInstance().getInjector("formulario.Formulario");
	}
	
}
