/*
 * generated by Xtext
 */
package formulario.validation

import org.eclipse.xtext.validation.Check
import Formularios_DASOFT.Formulario
import Formularios_DASOFT.Asercion
import formulario.parser.antlr.FormularioParser
import Formularios_DASOFT.Formularios_DASOFTPackage

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class FormularioValidator extends AbstractFormularioValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def validacionComprobacionCampos (Formulario form) {
		var flag = true;
		if (form.comprobacionCampos){
			flag = false;
			for(input : form.layout.entradas){
				
				for (accion : form.pruebas.acciones){
					if (accion.asercion.elemento == input){
						flag = true;
					}
				}

			}
			
			if (!flag){
				warning('El campo debe de estar incluido en al menos una asercion',
					Formularios_DASOFTPackage.Literals.FORMULARIO__COMPROBACION_CAMPOS,
					'faltaCampo')
				
			}
		}
		
	}
	
	@Check
	def validacionComprobacionAccion (Formulario form) {
		var flag = true;
		if (form.comprobacionAccion){
			flag = false;
			for(input : form.layout.entradas){
				
				for (accion : form.pruebas.acciones){
					if (accion.elemento == input){
						flag = true;
					}
				}

			}
			
			if (!flag){
				warning('El campo debe de estar incluido en al menos una accion',
					Formularios_DASOFTPackage.Literals.FORMULARIO__COMPROBACION_ACCION,
					'faltaAccion')
				
			}
		}
		
	}

}
