<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Formularios_DASOFT" nsURI="Formularios_DASOFT" nsPrefix="Formularios_DASOFT">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Formulario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//Layout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pruebas" eType="#//PruebaInterfaz"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comprobacionCampos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comprobacionAccion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnas" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entradas" upperBound="-1"
        eType="#//Input" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="prueba"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="habilitado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputTexto" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obligatorio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputBoton" abstract="true" eSuperTypes="#//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputMultiple" abstract="true" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valores" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputReaccion" abstract="true" eSuperTypes="#//InputMultiple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reaccion" lowerBound="1"
        eType="#//Reaccion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputRadio" eSuperTypes="#//InputReaccion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seleccion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputCombo" eSuperTypes="#//InputMultiple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seleccion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputCheck" eSuperTypes="#//InputReaccion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seleccion" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BotonValidar" eSuperTypes="#//InputBoton"/>
  <eClassifiers xsi:type="ecore:EClass" name="BotonGuardar" eSuperTypes="#//InputBoton"/>
  <eClassifiers xsi:type="ecore:EClass" name="BotonCancelar" eSuperTypes="#//BotonGuardar"/>
  <eClassifiers xsi:type="ecore:EClass" name="BotonCustom" eSuperTypes="#//InputBoton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="funcion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reaccion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objetivo" lowerBound="1"
        eType="#//Input"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activacion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReaccionVisible" eSuperTypes="#//Reaccion"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReaccionHabilitado" eSuperTypes="#//Reaccion"/>
  <eClassifiers xsi:type="ecore:EClass" name="PruebaInterfaz">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acciones" upperBound="-1"
        eType="#//Accion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento" lowerBound="1"
        eType="#//Input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asercion" lowerBound="1"
        eType="#//Asercion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccionValor" eSuperTypes="#//Accion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccionSeleccion" eSuperTypes="#//Accion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccionPulsacion" eSuperTypes="#//Accion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asercion" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento" lowerBound="1"
        eType="#//Input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsercionInvisible" eSuperTypes="#//Asercion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsercionHabilitado" eSuperTypes="#//Asercion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsercionValor" eSuperTypes="#//Asercion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsercionSeleccion" eSuperTypes="#//Asercion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
